OracleWebLogic/dockerfiles/12.1.3/.gitignore
OracleWebLogic/dockerfiles/12.1.3/Checksum.developer
OracleWebLogic/dockerfiles/12.1.3/Checksum.generic
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic
OracleWebLogic/dockerfiles/12.1.3/jdk-7u79-linux-x64.rpm.download
OracleWebLogic/dockerfiles/12.1.3/wls1213_dev_update2.zip.download

Update to Weblogic 12.1.3 update2 dev and OpenJDK 7u79

---

OracleWebLogic/dockerfiles/12.1.3/Checksum.developer
OracleWebLogic/dockerfiles/12.1.3/Checksum.generic
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic
OracleWebLogic/dockerfiles/12.1.3/jdk-7u79-linux-x64.rpm.download
OracleWebLogic/dockerfiles/12.1.3/jdk-8u51-linux-x64.rpm.download
OracleWebLogic/dockerfiles/12.1.3/wls1213_dev_update3.zip.download

WLS 12.1.3u3 (developer .zip distro) and JDK8u51.

Updated checksums, Dockerfiles, and download parameter files to use current WLS & JDK builds

---

OracleWebLogic/dockerfiles/12.1.3/.gitignore
OracleWebLogic/dockerfiles/12.1.3/Checksum.developer
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.1.3/wls1213_dev_update3.zip.download

Couldn't find the update2 on the Oracle site, only update3. Updated the code to use update3 instead. Building the developer image works. Likely need some work to do the generic images as well.

Changed from weblogic update2 to update3

---

OracleWebLogic/dockerfiles/12.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.infrastructure

Missed these on the first pull request.

Updated FROM to reference official Oracle images.

---

OracleWebLogic/dockerfiles/12.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic
OracleWebLogic/dockerfiles/12.1.3/server-jre-8u65-linux-x64.tar.gz.download
OracleWebLogic/dockerfiles/12.2.1/Checksum.developer
OracleWebLogic/dockerfiles/12.2.1/Checksum.generic
OracleWebLogic/dockerfiles/12.2.1/Checksum.infrastructure
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.infrastructure
OracleWebLogic/dockerfiles/12.2.1/server-jre-8u65-linux-x64.tar.gz.download

Reverts oracle/docker-images#61

Revert "Name of the JRE download should be "server-jre-8u65-linux-x64.gz""

---

OracleHTTPServer/README.md
OracleHTTPServer/dockerfiles/COPYRIGHT
OracleHTTPServer/dockerfiles/Dockerfile
OracleHTTPServer/dockerfiles/LICENSE
OracleHTTPServer/dockerfiles/buildDockerImage.sh
OracleHTTPServer/dockerfiles/fmw_12.2.1.0.0_ohs_linux64_Disk1_1of1.zip.download
OracleHTTPServer/dockerfiles/ohssainstall.file
OracleHTTPServer/dockerfiles/oraInst.loc
OracleHTTPServer/dockerfiles/server-jre-8u77-linux-x64.tar.gz.download
OracleHTTPServer/samples/1221-OHS-domain/Dockerfile
OracleHTTPServer/samples/1221-OHS-domain/README.md
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/commEnv.sh
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/configureWLSProxyPlugin.sh
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/create-sa-ohs-domain.py
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/helloWorld.html
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/mod_wl_ohs.conf.sample
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/restart-ohs.py
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/restartOHS.sh
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/start-ohs.py
OracleHTTPServer/samples/1221-OHS-domain/container-scripts/startNMandOHS.sh

Checking in the first set of files for official Oracle HTTP Server 12.2.1 Dockerfile, samples and scripts. Reviewed done by
michael.meiner@oracle.com
bruno.borges@oracle.com

Oracle HTTP Server 12.2.1 Docker files samples

---

OracleHTTPServer/README.md
OracleHTTPServer/samples/1221-ohs-domain/README.md

Edited with markdown formatting for directives example

Edited with markdown formatting for directives example

---

OracleWebLogic/dockerfiles/12.2.1/Dockerfile.developer
OracleWebLogic/samples/1221-domain/Dockerfile
OracleWebLogic/samples/1221-domain/container-scripts/create-wls-domain.py

If WebLogic Server is built as developer mode, enable debug mode and production mode is dev.

Running WebLogic Server as Developer mode.

---

OracleWebLogic/dockerfiles/12.2.1.1/container-scripts/createAndStartEmptyDomain.sh

Made two changes to the script:
1) Change the formula that generates the password to make sure it always has alpha and numeric characters
2)Check if there is already a domain created before calling create_wls_domain.py

Changes to script createAndStartEmptyDomain.sh

---

OracleWebLogic/samples/1221-domain-with-resources/README.md

For Issue #144

---

OracleDatabase/samples/prebuiltdb/README.md

Hi
Added an sample README for how-to create an image with a prebuilt database. You can consider if you want to use it.
Regards,
Lasse Jenssen

OracleDatabase: Added sample/prebuiltdb/README.md

---

ContainerCloud/images/docker-hello-world/index.html

Reverts oracle/docker-images#247

Revert "Update index.html"

---

OracleWebLogic/README.md

Add a link to Oracle Container Registry to get pre-built images

Add a link to Oracle Container Registry 

---

OracleDatabase/dockerfiles/12.1.0.2/installPerl.sh

Makes #270 a lot easier to spot.

ensure errors in installPerl.sh are caught

---

OracleJava/java-7/Dockerfile
OracleJava/java-8/Dockerfile
OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.generic

Changes to OracleJava and WebLogic 12.2.1.1 and 12.2.1.2 Dockerfiles to extend the OL 7-slim image

Changes to Dockerfiles to extend the OL 7-slim image

---

OracleWebLogic/dockerfiles/12.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1/Dockerfile.infrastructure
OracleWebLogic/samples/1221-appdeploy/README.md
OracleWebLogic/samples/1221-docker-compose/docker-compose.yml
OracleWebLogic/samples/1221-domain-with-resources/README.md
OracleWebLogic/samples/1221-domain/Dockerfile
OracleWebLogic/samples/1221-domain/README.md
OracleWebLogic/samples/1221-domain/container-scripts/add-server.py
OracleWebLogic/samples/1221-domain/container-scripts/commonfuncs.py
OracleWebLogic/samples/1221-domain/container-scripts/create-wls-domain.py
OracleWebLogic/samples/1221-multihost/setenv.sh
OracleWebLogic/samples/1221-multihost/start-webtier.sh
OracleWebLogic/samples/1221-webtier-apache/Dockerfile
OracleWebLogic/samples/1221-webtier-apache/README.md

Remove yum install util-linux and remove su to make image as small as possible.
Move common commands to the head of Dockerfiles to reutilize layers across different WLS version images.
Standardize the use of port numbers, admin port 7001, managed server port 7002

Remove yum install util-linux

---

OracleTuxedo/dockerfiles/12.1.3/Dockerfile

invoke install.sh instead of tuxedo12.1.3_silent_install.sh

Fix Dockerfile for Tuxedo

---

GlassFish/4.1.2-web/Dockerfile
GlassFish/4.1.2/Dockerfile

Adding docker file for GlassFish 4.1.2 release both for full profile and for web profile

adding docker file for GlassFish 4.1.2 release

---

OracleWebLogic/samples/1221-domain-with-resources/Dockerfile
OracleWebLogic/samples/1221-domain-with-resources/README.md
OracleWebLogic/samples/1221-domain-with-resources/build.sh
OracleWebLogic/samples/1221-domain-with-resources/container-scripts/ds-deploy.py
OracleWebLogic/samples/1221-domain-with-resources/container-scripts/jms-deploy.py
OracleWebLogic/samples/1221-domain/container-scripts/create-wls-domain.py

Persist the JMS Store to a volume on the host. Correction to AdminServer name in 1221-domain.

Persist the JMS Store to a volume on the host.

---

OracleWebLogic/samples/1221-appdeploy/container-scripts/app-deploy.py
OracleWebLogic/samples/1221-domain-with-resources/container-scripts/datasource.properties.derby
OracleWebLogic/samples/1221-domain-with-resources/container-scripts/datasource.properties.oracle
OracleWebLogic/samples/12212-oradb-medrec/Dockerfile
OracleWebLogic/samples/12212-oradb-medrec/README.md
OracleWebLogic/samples/12212-oradb-medrec/build.sh
OracleWebLogic/samples/12212-oradb-medrec/container-scripts/medrec-ds-deploy.py
OracleWebLogic/samples/12212-oradb-medrec/container-scripts/oradatasource.properties
OracleWebLogic/samples/12212-oradb-medrec/container-scripts/startSample.sh
OracleWebLogic/samples/12212-oradb-medrec/demo_oracle.ddl
OracleWebLogic/samples/12212-oradb-medrec/fmw_12.2.1.2.0_wls_supplemental_quick_Disk1_1of1.zip.download

Create sample for WebLogic medrec sample app connecting to Oracle DB running in containers 
Correct 12212-medrec Dockerfile
Allow for 1221-appdeploy for the Admin Server name to be set as an ENV var

Create sample for WebLogic medrec sample app connecting to Oracle DB running in containers 

---

NoSQL/4.3.11/Dockerfile

Adding VOLUME for persisting kvroot

---

OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/createAndStartEmptyDomain.sh
OracleWebLogic/samples/12211-patch/Dockerfile

…follows the LDAP Authentication Provider rules.  Change the 12.2.1.1 patching sample Dockerfile to not use su command.

WebLogic Server Admin Password auto generation & Patching sample Dockerfile improvments

---

ContainerCloud/images/rolling-router-sticky-sessions/wercker.yml

Example Wercker.yml for a node.js application for rolling router

Wercker sample yml for node.js

---

OracleDatabase/dockerfiles/12.1.0.2/setupLinuxEnv.sh
OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.ee
OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.se2
OracleDatabase/dockerfiles/12.2.0.1/setupLinuxEnv.sh

The file checkDBStatus.sh does not have execution permission

Lack Permission

---

OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.generic

Fixing up some issues with the older 12.2.1.1 Dockerfiles that I fixed while building images for the Oracle Container Registry.

Fixing up some issues with the 12.2.1.1 WLS Dockerfiles

---

README.md

Updated README with new location of Oracle Linux base images.

---

CONTRIBUTING.md

Clarify rule around SSH daemon.

---

CODEOWNERS

This may help us better organize who owns what :-)
More information: https://github.com/blog/2392-introducing-code-owners

Experiment code owners feature

---

CODEOWNERS

Whatever hits first is how CODEOWNERS works.

Adjust priority inside CODEOWNERS

---

NoSQL/4.4.6/Dockerfile.ee
NoSQL/README.md

I am adding a new Dockerfile for Oracle NoSQL Database EE (enterprise edition), also making related changes to README in NoSQL directory.

Add NoSQL EE Dockerfile and related README update

---

OracleJava/windows-java-8/server-jre-8u131-windows-x64.tar.gz.download

…ver-jre-8u131-windows-x64.tar.gz.download

Update .download for windows-server-jre8

---

OracleSOASuite/dockerfiles/README.md
OracleSOASuite/samples/README.md

Noticed that the README's were not rendering correctly on GIThub. Fixed the markup to take care of that. Other minor corrections in the README.

OracleSOASuite: README rendering fixes

---

OracleSOASuite/dockerfiles/README.md
OracleSOASuite/samples/README.md

I've made some further tweaks to the SOA Suite documentation. 
@rajlali can you review and approve these, please?

Further improvements to Markdown formatting for SOA Suite documentation.

---

OracleDatabase/tests/README.md
OracleDatabase/tests/runAllTests.sh
OracleDatabase/tests/runImageBuildTests.sh

These scripts provide some easier way of testing the impact of changes on the Docker image.

Provide change testing scripts

---

OracleWebLogic/samples/12212-msiserver/README.md
OracleWebLogic/samples/12212-msiserver/apps1.1/summercamps.ear/META-INF/application.xml
OracleWebLogic/samples/12212-msiserver/apps1.1/summercamps.ear/registration.war/WEB-INF/weblogic.xml
OracleWebLogic/samples/12212-msiserver/apps1.1/summercamps.ear/registration.war/index.jsp

Add rolling update example for 12212-msiserver sample.

Add rolling update example for msi server.

---

OracleSOASuite/LICENSE
OracleSOASuite/dockerfiles/12.2.1.2-soabpm/Dockerfile
OracleSOASuite/dockerfiles/12.2.1.2-soabpm/container-scripts/createDomain.py
OracleSOASuite/dockerfiles/12.2.1.2-soabpm/container-scripts/createDomainAndStart.sh
OracleSOASuite/dockerfiles/12.2.1.2-soabpm/container-scripts/startAS.sh
OracleSOASuite/dockerfiles/12.2.1.2-soabpm/container-scripts/startMS.sh
OracleSOASuite/dockerfiles/12.2.1.2-soabpm/container-scripts/updListenAddress.py
OracleSOASuite/dockerfiles/buildDockerImage.sh

Added UPL 1.0 licensing information to all scripts.

Adding UPL 1.0 licensing to all scripts (OracleSOASuite)

---

OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile

Fix Dockerfile to do installation of FMW Infrastructure installer

Fixes to Dockerfile

---

OracleGoldenGate/README.md
OracleGoldenGate/dockerBuild.sh

- Revise documentation for latest version 12.3.0.1.0
- Update dockerBuild.sh to work with GA filenames

Oracle GoldenGate on Docker

---

OracleGoldenGate/README.md

- Add Contents section to README

Oracle GoldenGate

---

CONTRIBUTING.md
GlassFish/4.1.1-web/Dockerfile
GlassFish/4.1.1/Dockerfile
GlassFish/4.1.2-web/Dockerfile
GlassFish/4.1.2/Dockerfile
GlassFish/5.0-web/Dockerfile
GlassFish/5.0/Dockerfile
GlassFish/nightly-web/Dockerfile
GlassFish/nightly/Dockerfile
GraalVM/graalvm-0.22/Dockerfile
OpenJDK/java-6/Dockerfile
OpenJDK/java-7/Dockerfile
OpenJDK/java-8/Dockerfile
OracleBI/dockerfiles/12.2.1.2/Dockerfile
OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe
OracleDatabase/dockerfiles/12.1.0.2/setupLinuxEnv.sh
OracleDatabase/dockerfiles/12.2.0.1/setupLinuxEnv.sh
OracleFMWInfrastructure/dockerfiles/12.2.1.2/Dockerfile
OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile
OracleHTTPServer/dockerfiles/12.2.1.2.0/Dockerfile
OracleHTTPServer/dockerfiles/12.2.1.3.0/Dockerfile
OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile
OracleTuxedo/tsam/dockerfiles/12.2.2/Dockerfile

This resolves #555 by replacing all instances of `yum clean all` with `rm -rf /var/cache/yum` as the annoying new message suggests.
I'm going to tag a whole bunch of reviewers for each person to review their own `Dockerfile`.

Replacing yum clean all across the repo

---

OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe
OracleDatabase/dockerfiles/11.2.0.2/checkDBStatus.sh
OracleDatabase/dockerfiles/12.1.0.2/Dockerfile.ee
OracleDatabase/dockerfiles/12.1.0.2/Dockerfile.se2
OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.ee
OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.se2
OracleDatabase/dockerfiles/12.2.0.1/checkDBStatus.sh
OracleDatabase/tests/runAllTests.sh
OracleDatabase/tests/runContainerTests.sh
OracleDatabase/tests/runImageBuildTests.sh

This PR introduces `HEALTHCHECK` for all Oracle database images as well as a minor bug fix in the test scripts.
All changes have run successfully through all tests.

Introduction of health checks + tests bug fix

---

OracleJava/README.md
OracleJava/java-9/Dockerfile
OracleJava/java-9/build.sh
OracleJava/java-9/serverjre-9.0.1_linux-x64_bin.tar.gz.download

Create the folders to add a server JRE 9 image for Linux

Aureliogrb java 9

---

OracleDataIntegrator/README.md
OracleDataIntegrator/dockerfiles/12.2.1.3.0/Dockerfile
OracleDataIntegrator/dockerfiles/12.2.1.3.0/container-scripts/CreateODIDomain.py
OracleDataIntegrator/dockerfiles/12.2.1.3.0/container-scripts/CreateODIDomainandRunAgent.sh
OracleDataIntegrator/dockerfiles/12.2.1.3.0/db.env.list
OracleDataIntegrator/dockerfiles/12.2.1.3.0/fmw_12.2.1.3.0_odi_Disk1_1of2.zip.download
OracleDataIntegrator/dockerfiles/12.2.1.3.0/fmw_12.2.1.3.0_odi_Disk1_2of2.zip.download
OracleDataIntegrator/dockerfiles/12.2.1.3.0/odi.env.list
OracleDataIntegrator/dockerfiles/12.2.1.3.0/oraInst.loc
OracleDataIntegrator/dockerfiles/buildDockerImage.sh

New Oracle Data Integrator Docker scripts for 12.2.1.3.0

Oracle Data Integrator - 12.2.1.3.0 Docker scripts

---

OracleJava/java-9/Dockerfile

server jre filename is incorrect.

JAVA_PKG not found as JRE filename incorrect.

---

OracleRestDataServices/dockerfiles/buildDockerImage.sh

Fix issue (#644) with setting `VERSION` in macOS bash

#644 fix issue with setting VERSION in macOS bash

---

OracleSOASuite/dockerfiles/12.2.1.2/Dockerfile
OracleSOASuite/dockerfiles/12.2.1.3/Dockerfile
OracleSOASuite/setenv.sh

- Updates to both 12.2.1.2 and 12.2.1.3 to handle the hostname missing because container-registry image for serverjre has this but not the latest on GIThub.
- Updated to clear the yum cache
Thanks. Raj...

OracleSOASuite: Updated to add hostname to image as JRE uses 7-slim now

---

OracleEDQ/12.2.1.3.0/Dockerfile
OracleEDQ/12.2.1.3.0/EDQServer.env.list
OracleEDQ/12.2.1.3.0/container-scripts/CreateEDQDomain.py
OracleEDQ/12.2.1.3.0/container-scripts/CreateEDQDomainandStart.sh
OracleEDQ/12.2.1.3.0/container-scripts/domain.py
OracleEDQ/12.2.1.3.0/container-scripts/edq.py
OracleEDQ/12.2.1.3.0/container-scripts/startManagedServer.sh
OracleEDQ/12.2.1.3.0/edq.db_env.list
OracleEDQ/12.2.1.3.0/fmw_12.2.1.3.0_edq_Disk1_1of1.zip.download
OracleEDQ/12.2.1.3.0/oraInst.loc
OracleEDQ/LICENSE
OracleEDQ/README.md
OracleEDQ/buildDockerImage.sh

Initial EDQ 12.2.1.3.0 Docker Scripts

EDQ 12.2.1.3.0 Docker Scripts

---

OracleWebLogic/samples/wls-K8s/wls-12213-domain/Dockerfile

Correct permissions of scripts in the domain image

Correct permissions of scripts in the domain image

---

OracleDatabase/dockerfiles/buildDockerImage.sh

Removed unnecessary return check and reformatted error message.

Fix for #702

---

CODEOWNERS

Add prashanthnagaraja to list (OracleSOASuite)

Add prashanthnagaraja (SOA owner) to the list

---

OracleWebCenterSites/README.md
OracleWebCenterSites/dockerfiles/12.2.1.3/sites-container-scripts/createSitesDomainandStartAdmin.sh
OracleWebCenterSites/dockerfiles/12.2.1.3/wcs-wls-docker-install/bootstrap.properties
OracleWebCenterSites/dockerfiles/12.2.1.3/wcs-wls-docker-install/src/main/groovy/com/oracle/wcsites/install/Utils.groovy
OracleWebCenterSites/dockerfiles/wcsitesadminserver.env.list

Taking credentials as input during installation.

Parameterize Application passwords

---

OracleWebCenterSites/README.md

updating instructions

---

OracleSOASuite/dockerfiles/README.md

Incorporated the review comment 'create a new user with the same uid:gid as the oracle user and give restrictive permission of 700'

Updated the doc to remove 777 permission

---

OracleDatabase/dockerfiles/11.2.0.2/runOracle.sh
OracleDatabase/dockerfiles/12.1.0.2/checkSpace.sh
OracleDatabase/dockerfiles/12.2.0.1/checkSpace.sh

Fix for #781

---

OracleDatabase/tests/runContainerTests.sh

Pass on correct SID for XE container test

Minor fix: XE unit test

---

OracleDatabase/FAQ.md

Update FAQ for volume permission question

---

README.md

Change the capitalisation of open source.

---

CODEOWNERS

New Codeowner for NoSQL

---

OracleWebLogic/README.md

Update README and fix broken links fix #802

Update README and fix broken links

---

OracleWebLogic/samples/12212-domain/README.md

Correction to version number in README 12212-domain, correct issue #832

Corrections to README

---

OracleDatabase/RAC/OracleRealApplicationClusters/README.md
OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/checkDBStatus.sh
OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/checkDBStatus.sh
OracleDatabase/SingleInstance/tests/runContainerTests.sh
OracleDatabase/SingleInstance/tests/runImageBuildTests.sh

This fixes bug #819 and introduces two test cases for it.

Fix lowercase pdb status check

---

OracleHTTPServer/dockerfiles/12.2.1.3.0/container-scripts/provisionOHS.sh
OracleHTTPServer/dockerfiles/12.2.1.3.0/container-scripts/useCustomHttpdConf.sh

In some situations we need to tune the parameters in httpd.conf. This change will provide for a way to do it.

Overriding httpd.conf

---

OracleWebLogic/samples/12213-webtier-apache/fmw_12.2.1.3.0_wlsplugins_Disk1_1of1.zip.download

Remove unintended space at the end of download file
Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>

Fix download file

---

OracleWebLogic/README.md
OracleWebLogic/dockerfiles/12.2.1.3/README.md
OracleWebLogic/samples/1221-domain/container-scripts/add-server.py
OracleWebLogic/samples/12212-domain/container-scripts/add-server.py
OracleWebLogic/samples/12213-domain/container-scripts/add-server.py

Correct README to include support information.
Correct add-server.py to make managed server listen address '' fix issue #852
Correct README to add -p port mapping

Correct README and make changes to make MS listenaddress blank

---

OracleWebLogic/samples/12213-webtier-apache/README.md
OracleWebLogic/samples/12213-webtier-apache/buildDockerImage.sh
OracleWebLogic/samples/12213-webtier-apache/custom_mod_wl_apache.conf.sample

Add recommendation about exposing admin port plus minor cleanup in README.md

---

OracleWebLogic/samples/12213-webtier-apache/Dockerfile

Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>
@mriccell

Add libaio to support SSL

---

OracleWebLogic/samples/12213-webtier-apache/README.md

Reviewed and edited new sections in README file

---

OracleRestDataServices/dockerfiles/Dockerfile

Specify GID and UID

---

OracleWebLogic/samples/12213-domain-wdt/Dockerfile

Only copy WDT archive file and not all files under archive directory

Only copy archive file and not all files under archive directory

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/18.3.0/Dockerfile

Introduces 18.3 instant client.

Update with 18.3 InstantClient

---

OracleDatabase/SingleInstance/dockerfiles/18.3.0/createDB.sh

Fix local_listener parameter in Oracle DB

---

OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/installDBBinaries.sh
OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/installDBBinaries.sh
OracleDatabase/SingleInstance/dockerfiles/18.3.0/installDBBinaries.sh
OracleDatabase/SingleInstance/tests/helperFunctions.sh
OracleDatabase/SingleInstance/tests/runContainerTests183.sh

One of the few prerequisites for #946.

Further size reduction of image

---

OracleDatabase/SingleInstance/README.md

Just a little typo of versions fixed.

chore: Update README.MD on OracleDatabase

---

README.md

A little more clarity should help.

Update README so that issues/bugs are reported on GitHub.

---

OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/setupLinuxEnv.sh
OracleDatabase/SingleInstance/dockerfiles/18.3.0/setupLinuxEnv.sh

Remove tar requirement

---

OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.1/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.1/README.md
OracleWebLogic/dockerfiles/12.2.1.1/container-scripts/create-wls-domain.py
OracleWebLogic/dockerfiles/12.2.1.1/container-scripts/createAndStartEmptyDomain.sh
OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.2/README.md
OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/create-wls-domain.py
OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/createAndStartEmptyDomain.sh

Changes to secure Admin Authentication

Changes to secure Admin Authentication

---

OracleWebLogic/dockerfiles/12.2.1.1/README.md
OracleWebLogic/dockerfiles/buildDockerImage.sh

Changes to builDockerImage.sh to remove INFRASTRUCTURE option and README of 12.2.1.1

Changes to builDockerImage.sh to remove INFRASTRUCTURE option

---

OracleRestDataServices/dockerfiles/buildDockerImage.sh

Match regex with new version format

---

README.md

Updating README.md to remove GlassFish and add GraalVM.

---

OracleWebLogic/samples/12213-domain-wdt/README.md

Fix documentation

---

OracleWebLogic/dockerfiles/12.2.1.1/container-scripts/create-wls-domain.py
OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/create-wls-domain.py
OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/create-wls-domain.py

Set WebLogic username to the one read from domain.properties resolve  issue #1004

Set WebLogic username to the one read from domain.properties 

---

OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/18.3.0/runOracle.sh

Include check for hostname - fix for #711

Check hostname on container startup for invalid characters

---

OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/Dockerfile.ee
OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/Dockerfile.se2
OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/Dockerfile
OracleDatabase/SingleInstance/dockerfiles/18.3.0/Dockerfile

Include chmod before calling DB binaries install

---

OracleWebLogic/samples/wls-K8s/README.md

Add README to make reference to the new Prometheus and Grafana sample location.

Add README to make reference to the new Prometheus and Grafana sample location.

---

OracleWebLogic/samples/12213-domain-home-in-image/Dockerfile
OracleWebLogic/samples/12213-domain-home-in-image/README.md
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/create-wls-domain.py
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/createWLSDomain.sh
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startAdminServer.sh
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startManagedServer.sh
OracleWebLogic/samples/12213-domain-home-in-image/properties/domain.properties
OracleWebLogic/samples/12213-domain-home-in-image/properties/domain_security.properties
OracleWebLogic/samples/12213-domain-home-in-image/properties/runtime.properties
OracleWebLogic/samples/12213-domain/Dockerfile

Provide environment variables via properties files.  Set defaults to environment variables to align with domain-home in image sample in K8S project.

Provide environment variables through properties files

---

OracleWebLogic/samples/12213-domain-home-in-image/README.md
OracleWebLogic/samples/12213-patch-opatch-update/Dockerfile
OracleWebLogic/samples/12213-patch-opatch-update/README.md
OracleWebLogic/samples/12213-patch-opatch-update/p27117282_122130_Generic.download
OracleWebLogic/samples/12213-patch-opatch-update/p28186730_139400_Generic.download

Create sample to upgarde OPatch  this is required as a prerequisite to apply the Oct WLS 12.2.1.3 PSU

Create sample to upgarde OPatch 

---

OracleDatabase/SingleInstance/tests/runImageBuildTests.sh

Include 18c XE build in tests

---

OracleDatabase/SingleInstance/README.md

Fix uid for 11.2 XE in ReadMe

---

OracleWebLogic/samples/12213-domain-home-in-image/README.md
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/create-wls-domain.py
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startAdminServer.sh
OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startManagedServer.sh
OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-build/domain.properties
OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-run/security.properties

Remove configuration of DERBY DB from sample

Remove configuration of DERBY DB from sample

---

OracleWebLogic/samples/12213-domain-home-in-image-wdt/Dockerfile
OracleWebLogic/samples/12213-domain-home-in-image-wdt/README.md
OracleWebLogic/samples/12213-domain-home-in-image-wdt/build.sh
OracleWebLogic/samples/12213-domain-home-in-image-wdt/container-scripts/startAdminServer.sh
OracleWebLogic/samples/12213-domain-home-in-image-wdt/properties/docker-build/domain.properties
OracleWebLogic/samples/12213-domain-home-in-image-wdt/properties/docker-run/security.properties

1. Remove derby data source. Set the DERBY_FLAG=false in the admin server
2. add JAVA_HOME requirement. 
3. fix bash specific command in build.sh

Remove derby data source

---

OracleWebLogic/samples/12213-domain-home-in-image/Dockerfile
OracleWebLogic/samples/12213-patch-wls-for-k8s/Dockerfile.patch-ontop-12213
OracleWebLogic/samples/12213-patch-wls-for-k8s/Dockerfile.patch-ontop-12213-psu
OracleWebLogic/samples/12213-patch-wls-for-k8s/README.md
OracleWebLogic/samples/12213-patch-wls-for-k8s/build.sh

1-Change copyright dates
2-Clarify difference between Dockerfiles
3- Fix formatting
4- Clarify in Dockerfile to comment out commands when patch 27117282 is not required
5- Fix issue #1116

Changes to Copyright dates, Clarify patches to apply

---

OracleFMWInfrastructure/README.md
OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile

fix Dockerfile under OracleFMWInfrastructure 12.2.1.3

---

OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/create-wls-domain.py

Remove set('Id', 1) from create-wls-domain.py

Remove set('Id', 1) from create-wls-domain.py

---

OracleJava/README.md
OracleJava/java-8/server-jre-8u201-linux-x64.tar.gz.download
OracleJava/windows-java-8/build.sh
OracleJava/windows-java-8/nanoserver/Dockerfile
OracleJava/windows-java-8/server-jre-8u181-windows-x64.tar.gz.download
OracleJava/windows-java-8/windowsservercore/Dockerfile

Updated the version to 8u201 and removed the windows build package.

Aureliogrb jan2019 cpu

---

OracleDatabase/SingleInstance/dockerfiles/18.4.0/setPassword.sh

Fix for bug #1213

---

OracleDatabase/SingleInstance/FAQ.md

Signed-off-by: Jurrie Overgoor <1213142+Jurrie@users.noreply.github.com>

Explain how to synchronize the timezone of a container with Docker host

---

OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
OracleDatabase/SingleInstance/dockerfiles/18.4.0/checkSpace.sh

Introduce space check for XE

---

OracleFMWInfrastructure/README.md
OracleFMWInfrastructure/dockerfiles/12.2.1.3/README.md

1-Create a general FMW Infra project README that describes the main binary image and samples under the project
2-A dockerfile specific README

Improvements to the FMW Infrastructure READMEs

---

OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile
OracleFMWInfrastructure/samples/12213-domain-in-volume/Dockerfile
OracleFMWInfrastructure/samples/12213-domain-in-volume/Dockerfile.rcu
OracleFMWInfrastructure/samples/12213-domain-in-volume/container-scripts/createRCU.sh
OracleFMWInfrastructure/samples/12213-domain-in-volume/container-scripts/startFMWManagedServer.sh

1- Fix DOMAIN_HOME_ROOT URL
2- In Path refer to JAVA_HOME instead of hard coding the java home path
3- Fix reference to RCUPREFIX parameter in createRCU script
4- Correct comments in startFMWManagedServer script

Fixes to the 12213-domain-in-volume sample

---

OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/createDB.sh
OracleDatabase/SingleInstance/dockerfiles/18.3.0/createDB.sh

Enable EM global port

---

OracleCoherence/samples/122132-patch-for-k8s/Dockerfile
OracleCoherence/samples/122132-patch-for-k8s/README.md
OracleCoherence/samples/122132-patch-for-k8s/p29204496_122130_Generic.download

Added instructions to patch the Oracle Coherence image with the necessary patch to run Coherence on Kubernetes

Added instructions to patch the Oracle Coherence image with the necessary patch to run Coherence on Kubernetes

---

OracleDatabase/SingleInstance/README.md
OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh

Update ReadMe & build script

---

OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile
OracleFMWInfrastructure/dockerfiles/12.2.1.3/README.md

1) Improve Dockerfile to make image smaller
2) Fix install of libaio library
3) Remove VOLUME directive
4) Correct README to indicate to use -v to map domain home to host volume

Fix OracleFMWInfrastructure image

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/19/Dockerfile

This PR is doc and comment updates to make it easier for people to find optional packages

Describe optional Instant Client packages

---

OracleWebLogic/dockerfiles/12.2.1.3/README.md
OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/createAndStartEmptyDomain.sh

1) Export Domain_Home so that the domain can be created
2) Correct formatting of the Docker command in README

Fix export of DOMAIN_HOME, fix formatting of README

---

OracleFMWInfrastructure/README.md
OracleFMWInfrastructure/dockerfiles/12.2.1.3/README.md
OracleFMWInfrastructure/samples/12213-domain-in-volume/README.md
OracleFMWInfrastructure/samples/12213-patch-fmw-for-k8s/README.md

Review and edit project README files.

edit READMEs

---

OracleInstantClient/README.md

Remove 'files files' and align variable version syntax

Remove duplication and simplify

---

OracleWebCenterSites/dockerfiles/12.2.1.3/sites-container-scripts/createSitesDomainandStartAdmin.sh
OracleWebCenterSites/dockerfiles/12.2.1.3/wcs-wls-docker-install/bootstrap.properties
OracleWebCenterSites/dockerfiles/12.2.1.3/wcs-wls-docker-install/config.py
OracleWebCenterSites/dockerfiles/12.2.1.3/wcs-wls-docker-install/src/main/groovy/com/oracle/wcsites/install/Weblogic.groovy
OracleWebCenterSites/dockerfiles/buildDockerImage.sh
OracleWebCenterSites/dockerfiles/wcsitesadminserver.env.list

Update createWCSitesConfig.py in standard with WLS/Infra, parameterizing the names (machine, cluster and managed server)

Update createWCSitesConfig.py in standard with WLS/Infra, parameterizing the names (machine, cluster and managed server)

---

OracleCoherence/docs/00.imageusage/README.md
OracleCoherence/docs/1.clustering/README.md
OracleCoherence/docs/2.extend/README.md
OracleCoherence/docs/5.monitoring/README.md
OracleCoherence/docs/README.md

Fix formatting issues in the Coherence doc files.

fix doc pages formatting

---

OracleCoherence/README.md
OracleCoherence/samples/122133-patch-for-k8s/Dockerfile
OracleCoherence/samples/122133-patch-for-k8s/README.md
OracleCoherence/samples/122133-patch-for-k8s/p29961519_122130_Generic.download

Signed-off-by: Tim Middleton <tim.middleton@oracle.com>

Add instructions for patch of Coherence to 12.2.1.3.3.

---

OracleJava/java-8/server-jre-8u221-linux-x64.tar.gz.download

Updated the filename and the checksum

Updated the serverJRE version from 8u211 to 8u221

---

OracleDatabase/SingleInstance/FAQ.md

Update FAQ for native compilation

---

OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/12.2.0.1/Dockerfile

These two fixes define missing environment variables which prevented image from building.

Fixes to Dockerfile for OracleDatabase RAC

---

GraalVM/CE/19/Dockerfile

GraalVM CE 19.2.0 release

---

OracleBI/README.md
OracleBI/dockerfiles/12.2.1.4/Checksum.md5
OracleBI/dockerfiles/12.2.1.4/Dockerfile
OracleBI/dockerfiles/12.2.1.4/createAndStartDomain.sh
OracleBI/dockerfiles/12.2.1.4/fmw_12.2.1.4.0_bi_linux64_Disk1_1of2.zip.download
OracleBI/dockerfiles/12.2.1.4/fmw_12.2.1.4.0_bi_linux64_Disk1_2of2.zip.download
OracleBI/dockerfiles/12.2.1.4/install.file
OracleBI/dockerfiles/12.2.1.4/oraInst.loc
OracleBI/dockerfiles/12.2.1.4/wait_for_db.sh

OracleBI:
* Add support for OBIEE 12.2.1.4
* Updates to the README

Support obiee 12.2.1.4

---

GraalVM/CE/19/Dockerfile

New GraalVM CE 19.2.0.1 release

GraalVM CE 19.2.0.1 release

---

OracleCoherence/README.md
OracleCoherence/dockerfiles/12.2.1.4.0/pom.xml
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/assemble/coherence.xml
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/Dockerfile
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/extend-cache-config.xml
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/install.file
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/logging.properties
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/oraInst.loc
OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/start.sh

Instructions to create Docker image for Coherence 12.2.1.4.0

Add Coherence 12.2.1.4

---

OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.slim

Converted the WebLogic 12.2.1.4 Dockerfiles to be multistage to reduce final created image size.

Multistage Dockerfiles for WebLogic 12.2.1.4

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/19/Dockerfile

Give more guidance on using wallets with Instant Client and show volume mount syntax.

Add specific wallet instructions for Instant Client

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/19/Dockerfile

Update some URLS, mostly to use https.  Restructure the Dockerfile doc content and add headings

Update URLs and restructure Instant Client doc

---

OracleJava/java-8/Dockerfile
OracleJava/java-8/server-jre-8u231-linux-x64.tar.gz.download

This is now closer to what is done on OpenJDK makefiles

Updated the docker file to match what we do with the JDK 11 docker file

---

OracleWebLogic/dockerfiles/12.2.1.4/Checksum.generic
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.slim
OracleWebLogic/dockerfiles/12.2.1.4/README.md

Correct permissions to /u01 in Dockerfiles
Add statement that clarifies that we support multi-server as well as single-server domain.

Correct permissions in 12.2.1.4 images

---

GraalVM/CE/19/Dockerfile

Fix for: https://github.com/oracle/graal/issues/1891

Added libstdc++-static package

---

OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/create-wls-domain.py

Reverts oracle/docker-images#1451

Revert "Read SSL_ENABLED from the env in case it's not provided in the docker…"

---

OracleDatabase/SingleInstance/FAQ.md

To document the difference between the Dockerfiles in this repo and the images hosted on Oracle Container Registry and Docker Hub.

Updating Single Instance DB FAQ 

---

OracleDatabase/RAC/OracleRealApplicationClusters/README.md

update rac readme w/missing backslash

---

OracleDatabase/RAC/OracleRACStorageServer/dockerfiles/12.2.0.1/runOracle.sh
OracleDatabase/RAC/OracleRACStorageServer/dockerfiles/18.3.0/runOracle.sh
OracleDatabase/RAC/OracleRACStorageServer/dockerfiles/19.3.0/runOracle.sh

Change 'Assining' to 'Assigning'

Fix typo in the RAC storage Server runOracle.sh files

---

OracleWebCenterSites/dockerfiles/12.2.1.4/Dockerfile
OracleWebCenterSites/dockerfiles/12.2.1.4/README.md
OracleWebCenterSites/dockerfiles/12.2.1.4/sites-container-scripts/createSitesDomainandStartAdmin.sh
OracleWebCenterSites/dockerfiles/12.2.1.4/wcs-wls-docker-install/config.py
OracleWebCenterSites/dockerfiles/12.2.1.4/wcs-wls-docker-install/src/main/groovy/com/oracle/wcsites/install/Utils.groovy
OracleWebCenterSites/dockerfiles/12.2.1.4/wcs-wls-docker-install/src/main/groovy/com/oracle/wcsites/install/Weblogic.groovy
OracleWebCenterSites/dockerfiles/buildDockerImage.sh

Hi,
This PR request consist of changes related to make JAVA_HOME location generic and updating readme and copyright notice.
Please review and approve this PR.
Thanks
Ashish

Making JAVA_HOME generic and updating readme and copyright notice

---

OracleDatabase/SingleInstance/dockerfiles/18.4.0/Checksum.xe
OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh

Remove XE download requirement

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/19/Dockerfile

Update for Instant Client 19.6

---

OracleWebLogic/dockerfiles/14.1.1.0/Checksum.developer
OracleWebLogic/dockerfiles/14.1.1.0/Checksum.generic
OracleWebLogic/dockerfiles/14.1.1.0/Checksum.slim
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.developer
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.generic
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.slim
OracleWebLogic/dockerfiles/14.1.1.0/README.md
OracleWebLogic/dockerfiles/14.1.1.0/container-scripts/create-wls-domain.py
OracleWebLogic/dockerfiles/14.1.1.0/container-scripts/createAndStartEmptyDomain.sh
OracleWebLogic/dockerfiles/14.1.1.0/fmw_14.1.1.0.0_wls_Disk1_1of1.zip.download
OracleWebLogic/dockerfiles/14.1.1.0/fmw_14.1.1.0.0_wls_quick_Disk1_1of1.zip.download
OracleWebLogic/dockerfiles/14.1.1.0/fmw_14.1.1.0.0_wls_quick_slim_Disk1_1of1.zip.download
OracleWebLogic/dockerfiles/14.1.1.0/install.file
OracleWebLogic/dockerfiles/14.1.1.0/oraInst.loc
OracleWebLogic/dockerfiles/14.1.1.0/properties/domain.properties

Adding WLS 14.1.1.0 JDK 11 images

Adding WLS 14.1.1.0 images

---

CODEOWNERS
OracleLinuxDevelopers/README.md
OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile

Also update `CODEOWNERS` to reflect the correct ownership of that directory.

Add Node.js 12 with Oracle Database drivers

---

OracleLinuxDevelopers/oraclelinux7/golang/1.13/Dockerfile
OracleLinuxDevelopers/oraclelinux7/golang/1.14/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/10-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/10/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/12/Dockerfile
OracleLinuxDevelopers/oraclelinux7/php/7.4-apache-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/php/7.4-apache/Dockerfile
OracleLinuxDevelopers/oraclelinux7/php/7.4-cli-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/php/7.4-cli/Dockerfile
OracleLinuxDevelopers/oraclelinux7/php/7.4-fpm-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/php/7.4-fpm/Dockerfile
OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/python/3.6/Dockerfile

So there's no need to disable it any more.

The ol7_UEKR5 repo is no longer enabled by default

---

OracleDatabase/README.md

Added Sharding Github repo link.

Added info for Oracle Sharding

---

OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.generic

Change permissions of uid and group     OWLS-83349

Change permissions of uid and group

---

OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.developer
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.slim
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.developer-11
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.developer-8
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.generic-11
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.generic-8
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.slim-11
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.slim-8

Change permissions of user id and group (rest of Dockerfiles)

Change permissions of user id and group (rest of Dockerfiles)

---

OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/createAndStartEmptyDomain.sh
OracleWebLogic/dockerfiles/12.2.1.4/Checksum.generic
OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.generic
OracleWebLogic/dockerfiles/12.2.1.4/container-scripts/createAndStartEmptyDomain.sh
OracleWebLogic/dockerfiles/12.2.1.4/fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip.download
OracleWebLogic/dockerfiles/14.1.1.0/Checksum.developer
OracleWebLogic/dockerfiles/14.1.1.0/Checksum.generic
OracleWebLogic/dockerfiles/14.1.1.0/Checksum.slim
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.developer-11
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.developer-8
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.generic-11
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.generic-8
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.slim-11
OracleWebLogic/dockerfiles/14.1.1.0/Dockerfile.slim-8
OracleWebLogic/dockerfiles/14.1.1.0/container-scripts/createAndStartEmptyDomain.sh
OracleWebLogic/dockerfiles/14.1.1.0/fmw_14.1.1.0.0_wls_lite_Disk1_1of1.zip.download
OracleWebLogic/dockerfiles/14.1.1.0/fmw_14.1.1.0.0_wls_lite_quick_Disk1_1of1.zip.download
OracleWebLogic/dockerfiles/14.1.1.0/fmw_14.1.1.0.0_wls_lite_slim_Disk1_1of1.zip.download

Switch WLS installers in 12.2.1.4 and 14.1.1.0 to lite installers.  Change permissions of the DOMAIN_HOME.

Switch WLS installers to lite installers

---

OracleCoherence/dockerfiles/12.2.1.3.0/Dockerfile.quickinstall
OracleCoherence/dockerfiles/12.2.1.3.0/Dockerfile.standalone

Re-organize commands in OracleCoherence DockerFiles for 12.2.1.3.0 to reduce image size

---

OracleDatabase/SingleInstance/README.md

Fixes small doc bug clarifying user scripts location for 11gR2. (issue #1662)

Fix doc bug (#1662)

---

OracleDatabase/SingleInstance/README.md

Fix for #1681

---

OracleJava/15/Dockerfile
OracleJava/15/build.sh
OracleOpenJDK/15/Dockerfile
OracleOpenJDK/15/build.sh

Added dockerfiles for JDK 15 and OpenJDK 15

JDK 15 and OpenJDK 15 Dockerfiles and build.sh

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile
OracleInstantClient/dockerfiles/18/Dockerfile
OracleInstantClient/dockerfiles/19/Dockerfile

"Docker" -> "Container" changes, as hinted at on Slack.

Instant Client comment and doc updates

---

OracleDatabase/SingleInstance/samples/README.md
OracleDatabase/SingleInstance/samples/kubernetes/README.md
OracleDatabase/SingleInstance/samples/kubernetes/kubernetes-example.yaml

Create an example of deploying Oracle Database 19c image using native Kubernetes objects.
Signed-off-by: Mark Cram <mark.cram@oracle.com>

Include Oracle Database Kubernetes example

---

CONTRIBUTING.md

Updating the contribution guide to include language and other recommendations and guidelines around documentation standards.

Update the contribution guide 

---

OracleJava/11/Dockerfile
OracleJava/15/Dockerfile
OracleJava/8/Dockerfile
OracleOpenJDK/15/Dockerfile

Update Oracle JDK 11 to 11.0.9
Update Oracle JDK 15 to 15.0.1
Update Oracle OpenJDK 15 to 15.0.1
Update Oracle Server JRE 8 to 1.8.0_271

updated dockerfiles with Oct 2020 CPU releases

---

OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/18.3.0/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/18.4.0/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh

This issue addresses #1603.
@yunus-qureshi, @rishabh20, can you please review and also include the changes in the build automation for future images, please?

Remove SIGKILL trap as it cannot be trapped

---

OracleInstantClient/README.md
OracleInstantClient/dockerfiles/19/Dockerfile

Simple version update.
@Djelibeybi I'll add an OL8 Dockerfile next week.

Update for Instant Client 19.9

---

OracleIdentityGovernance/README.md
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/Dockerfile
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/README-OCR-Base.md
OracleIdentityGovernance/imagetool/12.2.1.4.0/README.md
OracleIdentityGovernance/imagetool/12.2.1.4.0/additionalBuildCmds.txt

cleanup README files to remove patch references
also cleaned up complete command outputs as suggested

cleanup README files to remove patch references

---

CODEOWNERS
README.md

Signed-off-by: Pratyush Dash <pratyush.dash@oracle.com>
Changed base README.md to add Oracle Access Management
Added name to CODEOWNERS.

Update base README

---

OracleIdentityGovernance/dockerfiles/buildDockerImage.sh

Fix license and copyright info in buildDockerImage.sh in the usage command

Fix license and copyright info in buildDockerImage.sh

---

OracleIdentityGovernance/dockerfiles/12.2.1.4.0/Dockerfile

use multi stage build in OIG Dockerfile as per guidelines

use multi stage build in OIG Dockerfile

---

OracleWebLogic/samples/12213-domain-home-in-image-wdt/Dockerfile
OracleWebLogic/samples/12213-domain-home-in-image-wdt/build.sh
OracleWebLogic/samples/12213-domain-home-in-image/Dockerfile

Change permissions for group in the DOMAIN_HOME.
Pull the latest WDT zip  before using.

Change permissions for group in the DOMAIN_HOME

---

CONTRIBUTING.md
OracleLinuxDevelopers/oraclelinux7/nodejs/10-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/12/Dockerfile
OracleLinuxDevelopers/oraclelinux7/nodejs/14/Dockerfile

- Added Dockerfile for Node.js 14 (no 14-oracledb yet, as that's pending release)
- Changed Dockerfiles for Node.js 10 and 12 to disable/enable yum repos as appropriate

Updates for nodejs 14

---

CODEOWNERS

Welcome @rjeberhard and @mark-au to the team. :) 

Please welcome two new maintainers to the oracle/docker-images repo.

---

OracleIdentityGovernance/imagetool/12.2.1.4.0/additionalBuildCmds.txt

fix imagetool container image build for OIG

fix imagetool container image build for OIG

---

OracleLinuxDevelopers/oraclelinux8/php/7.2-apache/Dockerfile
OracleLinuxDevelopers/oraclelinux8/php/7.3-apache/Dockerfile
OracleLinuxDevelopers/oraclelinux8/php/7.4-apache/Dockerfile
OracleLinuxDevelopers/oraclelinux8/php/7.4-apache/httpd.module
OracleLinuxDevelopers/oraclelinux8/php/7.4-apache/php.module
OracleLinuxDevelopers/oraclelinux8/php/7.4-cli/Dockerfile
OracleLinuxDevelopers/oraclelinux8/php/7.4-cli/php.module
OracleLinuxDevelopers/oraclelinux8/php/7.4-fpm/Dockerfile
OracleLinuxDevelopers/oraclelinux8/php/7.4-fpm/php.module

Add Oracle Linux 8 based container images for PHP 7.4.

---

CODEOWNERS
OracleLinuxDevelopers/README.md
OracleLinuxDevelopers/oraclelinux8/nodejs/10/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nodejs/10/nodejs.module
OracleLinuxDevelopers/oraclelinux8/nodejs/14/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nodejs/14/nodejs.module

README has been updated as well.

Add Node.js 14 for Oracle Linux 8 and switch the module profile

---

OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/createDomainAndStart.sh
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/createOIMDomain.py
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/startAdmin.sh
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/startMS.sh
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/updateListenAddress.py
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/updateListenAddressMS.py
OracleIdentityGovernance/samples/containerizedDB/docker-compose.yaml
OracleIdentityGovernance/samples/externalDB/docker-compose.yaml
OracleIdentityGovernance/setenv.sh

remove hard coded listen addresses for servers

OIG- remove hard coded listen addresses for servers

---

README.md

update root README with OUD and OUDSM

update root README with OUD and OUDSM

---

OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh

The `buildDockerImage.sh` script does not detect properly Podman on OL8 as:
- `docker version --format '{{.Server.Version | printf "%.5s" }}'` does return a version (OL7 version does not)
- `docker info --format '{{.host.BuildahVersion}}'` is an invalid format (should be `{{.Host.BuildahVersion}}`)
This PR address both issues for OL8 (podman 2.0.5) while keeping compatibility with OL7 (podman 1.6.4)
--

Improve podman detection for the OracleDatabase/SingleInstance buildDockerImage.sh  script

---

README.md

[docs] Fix broken links in README.md

---

OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Update Instant Client dockerfile labels

---

OracleInstantClient/README.md
OracleInstantClient/oraclelinux7/21/Dockerfile
OracleInstantClient/oraclelinux8/21/Dockerfile

Signed-off-by: Christopher Jones christopher.jones@oracle.com

Dockerfiles for Instant Client 21

---

OracleInstantClient/oraclelinux7/21/Dockerfile
OracleInstantClient/oraclelinux8/21/Dockerfile

Fix interop comment

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8-slim
OracleJava/15/Dockerfile
OracleJava/15/Dockerfile.8-slim
OracleJava/8/Dockerfile
OracleJava/8/Dockerfile.8-slim
OracleJava/README.md
OracleOpenJDK/15/Dockerfile
OracleOpenJDK/15/Dockerfile.8-slim

Updated the versions to those of the Jan 2021 Critical Patch Update

---

CODEOWNERS

Assigns just @AmedeeBulle and I as owners of the GitHub Actions 
workflow files.
The general improvements, efficiencies and clean-up included
at no extra cost.

[repo] Update code ownership for the GitHub Actions

---

.github/workflows/build-and-push-dev-images.yml
.github/workflows/build-and-push-nosql-image.yml

Update branch name in actions

---

OracleWebCenterContent/dockerfiles/12.2.1.4/Checksum
OracleWebCenterContent/dockerfiles/README.md
OracleWebCenterContent/dockerfiles/buildDockerImage.sh

Signed-off-by: Debojyoti Ghosh debojyoti.ghosh@oracle.com

Stage29jan

---

OracleWebCenterContent/dockerfiles/12.2.1.4/Dockerfile
OracleWebCenterContent/dockerfiles/README.md

DOCKERFILE modification to grant permission to scripts dir

---

OracleDatabase/SingleInstance/dockerfiles/18.4.0/runOracle.sh

This fixes #1533 
I have tested the patch only with oracle 18.04 xe, thus the PR only touches the container for that version.
The fix relies on `/etc/init.d/oracle-xe-18c configure` being able to correctly re-create the database from scratch after the files have been removed. I guess that that should work in other db versions too, but there might have been changes to the oracle init script, netca or dbca that I am not aware of...

Create new db on container start if oradata folder was manually emptied

---

OracleSOASuite/dockerfiles/12.2.1.4/README.md

This PR contains the SOA 12.2.1.4 documentation steps, for deploying a SOA domain in a multi-node environment.

soa 12.2.1.4 documentation update for docker based multihost deployment

---

OracleWebCenterContent/dockerfiles/README.md

Minor documentation changes to improve ease of use

---

OracleDatabase/SingleInstance/extensions/patching/Dockerfile
OracleDatabase/SingleInstance/extensions/patching/patchDBBinaries.sh

Exiting the build if patch application fails while building SI DB image with patching extension 

---

.github/workflows/build-and-push-instantclient-images.yml

A simplistic action that builds Instant Client 19 & 21 images for GHCR

Basic workflow to build Instant Client 19 and 21 GHCR images

---

.github/workflows/build-and-push-instantclient-images.yml
OracleInstantClient/README.md
OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux7/21/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile
OracleInstantClient/oraclelinux8/21/Dockerfile

The Instant Client README and Dockerfile comments now contain links to the new prebuilt containers.

Update Instant Client doc to link to the new prebuilt containers

---

OracleWebCenterContent/dockerfiles/12.2.1.4/Dockerfile
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/configureOrStartWebCenterContent.sh

DOCKERFILE cleanup and minor sctipt change

---

README.md

change oss.oracle.com to opensource.oracle.com

README url fix

---

OracleDatabase/SingleInstance/FAQ.md

fix: update Database FAQ to reflect the lack of support for M1 silicon

---

OracleInstantClient/README.md
OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Bump to Instant Client 19.11.
Mention the package registry.

Bump to Instant Client 19.11

---

OracleDatabase/SingleInstance/extensions/k8s/README.md

Including a section for properly perform operations that require Database shutdown/startup.

k8s extension Readme changes

---

OracleLinuxDevelopers/oraclelinux7/nodejs/14-oracledb/Dockerfile

feat: add oraclelinux7-nodejs:14-oracledb

---

OracleLinuxDevelopers/oraclelinux8/python/3.6-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux8/python/3.6-oracledb/python36.module

feat: add Oracle Linux 8 based Python 3.6 images with cx_Oracle

---

OracleLinuxDevelopers/oraclelinux8/nodejs/14-oracledb/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nodejs/14-oracledb/nodejs.module

New Dockerfile for OL8 with oracledb module for Node.js 14
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>

New Dockerfile for OL8 with oracledb module for Node.js 14

---

OracleLinuxDevelopers/oraclelinux7/golang/1.14/Dockerfile
OracleLinuxDevelopers/oraclelinux7/golang/1.15/Dockerfile
OracleLinuxDevelopers/oraclelinux7/golang/1.16/Dockerfile
OracleLinuxDevelopers/oraclelinux7/golang/Dockerfile

- updates for Go 1.16
- Revert "updates for Go 1.16"
- updates for golang 1.16

ol7 1.16 update

---

OracleAccessManagement/dockerfiles/12.2.1.4.0/Dockerfile
OracleAccessManagement/dockerfiles/12.2.1.4.0/container-scripts/get_healthcheck_url.sh

Added health check for the containers and also changes made so for oam containers to work on Openshift.

Added health check

---

OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/NOTES.txt

Changed Variable names in help text during helm install for IP and ports of loadBalancer

Modify Variable names in help text during helm install

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8-slim
OracleJava/16/Dockerfile
OracleJava/8/Dockerfile
OracleJava/8/Dockerfile.8-slim
OracleOpenJDK/16/Dockerfile

Added yum/microdnf -y update to get the latest updates on the underlying image during each build.

Update base image

---

OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile

fix(developper):  latest cx_Oracle requires latest instant client

---

OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile

This tidies up the previous PR.

The old Instant Client repo is not needed

---

OracleLinuxDevelopers/oraclelinux8/nodejs/14-oracledb/Dockerfile

Resolves #1987
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>

Change CMD from v to -v, fixes Issue 1987

---

OracleWebCenterContent/dockerfiles/12.2.1.4/Dockerfile
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/configureOrStartWebCenterContent.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/createDomainandStartAdmin.sh
OracleWebCenterContent/dockerfiles/README.md

User permission changes and minor doc changes.

User permission changes and minor doc changes

---

OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
OracleDatabase/SingleInstance/extensions/k8s/checkDBLockStatus.sh
OracleDatabase/SingleInstance/extensions/k8s/startDB.sh
OracleDatabase/SingleInstance/extensions/k8s/swapLocks.sh

Close #2006 
Fixed following issues:
- Removal of unwanted data appearing in logs after building k8s extension.
- Fixing tnsnames.ora overwriting issue.

Fixing issues in 19c

---

OracleLinuxDevelopers/README.md
OracleLinuxDevelopers/oraclelinux7/ruby/3.0/Dockerfile

Updated the `README.md` in `OracleLinuxDevelopers` to add Ruby 3 to the list and link to the `Dockerfile`

Updated README, added Ruby 3 to list.

---

OracleIdentityGovernance/dockerfiles/12.2.1.4.0/Dockerfile
OracleIdentityGovernance/imagetool/12.2.1.4.0/README.md
OracleIdentityGovernance/imagetool/12.2.1.4.0/additionalBuildCmds.txt
OracleIdentityGovernance/imagetool/12.2.1.4.0/buildArgs

Refresh the OIG Image build files

refresh OIG Image Build Files

---

OracleSOASuite/dockerfiles/12.2.1.4/Dockerfile
OracleSOASuite/dockerfiles/12.2.1.4/README.md
OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/createDomain.py
OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/startMS.sh
OracleSOASuite/dockerfiles/12.2.1.4/install/soasuite.download
OracleSOASuite/dockerfiles/12.2.1.4/install/soasuite.response
OracleSOASuite/dockerfiles/README.md
OracleSOASuite/dockerfiles/buildDockerImage.sh

Signed-off-by: Sambasiva Battagiri <sambasiva.battagiri@oracle.com>
Hi,
This pull request contains the Oracle SOA Suite Dockerfile, SOA createDomain script and Readme documentation updates as described below. Kindly review and merge the transaction.
**Dockerfile updates:**
1. Update the default user to oracle:root
2. Add b2b installer for installation purpose.
3. Install SOA libraries based on condition check
**README updates**
1. Updated latest instructions to build the SOA image.
2. Updated the SOA domain set up instructions with the latest supported domainTypes.
**SOA image build and domain creation script updates**
1. SOA image build script updated to remove the hard coding of versions.
2. SOA domain creation scripts updated to based on the latest supported domainTypes.

SOA Dockerfile and Readme updates to update user to oracle:root

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8-slim
OracleJava/16/Dockerfile
OracleJava/8/Dockerfile
OracleJava/8/Dockerfile.8-slim
OracleOpenJDK/16/Dockerfile

updated files for Jul 2021 CPU releases

---

OracleDatabase/SingleInstance/extensions/k8s/lock.py
OracleDatabase/SingleInstance/extensions/k8s/startDB.sh

Signed-off-by: Yunus Qureshi <write2yunus@gmail.com>

Enhance K8s extn for node failure cases

---

OracleDatabase/SingleInstance/extensions/k8s/lock.py

Enhanced lock.py by removing unnecessary checks causing the timing issue .

Handled Timing issue with acquiring/releasing locks

---

OracleGoldenGate/21c/bin/deployment-init.py
OracleGoldenGate/21c/install-prerequisites.sh

- Additional libraries for non-Oracle databases
- Minor fix to network re-configuration for Service Manager

Oracle GoldenGate in a Container

---

OracleDatabase/SingleInstance/dockerfiles/21.3.0/Checksum.ee
OracleDatabase/SingleInstance/dockerfiles/21.3.0/Checksum.se2
OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile
OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkDBStatus.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkSpace.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/createObserver.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/db_inst.rsp
OracleDatabase/SingleInstance/dockerfiles/21.3.0/dbca.rsp.tmpl
OracleDatabase/SingleInstance/dockerfiles/21.3.0/installDBBinaries.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/relinkOracleBinary.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/runUserScripts.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/setupLinuxEnv.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/startDB.sh

Support for building SingleInstance database 21c container images

---

OracleInstantClient/oraclelinux7/12.2.0.1/Dockerfile
OracleInstantClient/oraclelinux7/18/Dockerfile
OracleInstantClient/oraclelinux7/21/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile
OracleInstantClient/oraclelinux8/21/Dockerfile

Update Dockerfiles to use non-slim OL8 images per new guidelines

---

OracleInstantClient/README.md
OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Update to Instant Client 19.12

---

OracleWebCenterContent/dockerfiles/12.2.1.4/Dockerfile
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/configureOrStartCapture.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/configureOrStartIPM.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/configureOrStartWCCADF.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/createCaptureDomain_PS4.py
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/createDomainandStartAdmin.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/createIPMDomain_PS4.py
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/createWCCADFDomain_PS4.py
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/extendWithCaptureDomain.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/extendWithIPMDomain.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/extendWithWCCADFDomain.sh
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/setCaptureTopology.py
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/setIPMTopology.py
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/setWCCADFTopology.py
OracleWebCenterContent/dockerfiles/12.2.1.4/container-scripts/startAdminContainer.sh
OracleWebCenterContent/dockerfiles/README.md

Hi,
Please review my changes once. We are now extending the Oracle WCC Docker.
We are now including WCC Imaging , Capture and WCC ADFUI
Thanks,
Chaitanya.
Signed-off-by: chaitanya.malur <chaitanya.malur@oracle.com>

Changes in OracleWebCenterContent Docker to include IPM, Capture and ADFUI

---

OracleLinuxDevelopers/oraclelinux8/php/7.3-apache/Dockerfile
OracleLinuxDevelopers/oraclelinux8/ruby/2.7-nodejs/Dockerfile

fix: fix typos in two developer Dockerfiles

---

OracleLinuxDevelopers/oraclelinux7/golang/Dockerfile

chore: remove detached Dockefile from the repo

---

.github/workflows/build-and-push-dev-images.yml

Most scenarios tested in my fork -- looks OK...
--

ci(developper): update for the new oraclelinux8-compat image

---

OracleLinuxDevelopers/oraclelinux7/golang/1.17/Dockerfile

- adds golang 1.17 Dockerfile for OL7
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>

feat(developer): :sparkles: add golang 1.17 container

---

OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Update for Instant Client 19.13

Update for Instant Client 19.13

---

OracleWebCenterContent/dockerfiles/README.md

minor doc change

---

OracleLinuxDevelopers/oraclelinux8/golang/latest/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nginx/1.14/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nginx/1.18/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nginx/1.20/Dockerfile
OracleLinuxDevelopers/oraclelinux8/nodejs/16/Dockerfile
OracleLinuxDevelopers/oraclelinux8/ruby/3.0/Dockerfile

Also fixed a minor find and replace issue with some copyright headers.

feat: add images for new appstreams introduced with OL8U5

---

OracleDatabase/SingleInstance/README.md

Readme changes for Oracle Database 21c XE

---

OracleWebCenterSites/dockerfiles/12.2.1.4/sites-container-scripts/overrides/oui/startup-plan.xml

@Djelibeybi Please review and merge.
Added property weblogic.oif.serialFilterScope = weblogic

updaing weblogic property in startup-plan.xml

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8
OracleJava/11/build.sh
OracleJava/17/Dockerfile
OracleJava/17/build.sh
OracleJava/8/Dockerfile
OracleJava/8/Dockerfile.8
OracleJava/8/build.sh
OracleJava/README.md
OracleOpenJDK/17/Dockerfile
OracleOpenJDK/17/build.sh

updated versions to the Jan 2022 CPU releases

---

CONTRIBUTING.md

docs: update OCA url

---

.github/workflows/build-and-push-nosql-image.yml

Minor tweaks to the GitHub Action to build NoSQL CE image.

fix: adjust the login to GHCR for the NoSQL CE build action

---

OracleRestDataServices/dockerfiles/Dockerfile

Added tar, unzip utilities to Oracle Rest data Service Repository as it is required for OraOperator to install ORDS and APEX

Added tar, unzip utilities to ords

---

OracleSOASuite/dockerfiles/12.2.1.4/Dockerfile
OracleSOASuite/dockerfiles/12.2.1.4/README.md

This PR contains the SOA Dockerfile fixes to optimize the image size.
Signed-off-by: Sambasiva Battagiri <sambasiva.battagiri@oracle.com>

optimize SOA image size and doc corrections

---

OracleJava/18/Dockerfile
OracleJava/18/build.sh
OracleJava/README.md
OracleOpenJDK/18/Dockerfile
OracleOpenJDK/18/build.sh
OracleOpenJDK/README.md

Added files for creating OpenJDK/Oracle JDK 18 images

---

OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Update to Instant Client 19.14

---

OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
OracleDatabase/SingleInstance/dockerfiles/19.3.0/checkDBStatus.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/checkSpace.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/createObserver.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/db_inst.rsp
OracleDatabase/SingleInstance/dockerfiles/19.3.0/dbca.rsp.tmpl
OracleDatabase/SingleInstance/dockerfiles/19.3.0/installDBBinaries.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/relinkOracleBinary.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/runUserScripts.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/setPassword.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/setupLinuxEnv.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/startDB.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile
OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile.xe
OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkDBStatus.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkSpace.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/createObserver.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/db_inst.rsp
OracleDatabase/SingleInstance/dockerfiles/21.3.0/dbca.rsp.tmpl
OracleDatabase/SingleInstance/dockerfiles/21.3.0/installDBBinaries.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/relinkOracleBinary.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/runUserScripts.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/setupLinuxEnv.sh
OracleDatabase/SingleInstance/dockerfiles/21.3.0/startDB.sh

Changed copyright year for Oracle Database 19c and 21c scripts

---

OracleManagementAgent/README.md

Oracle Management Agent - update doc with install key cleanup steps

---

OracleGoldenGate/21c/README.md

docker commands are updated for MySQL and PostgreSQL.
The copyright year is also updated.

Changes after testing MySQL and PostgreSQL for docker

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

add sample agents management script

add sample agents management script

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

fix header as per review comment
@Djelibeybi

fix header as per review comment

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

Fix typos and formatting in agentManagment.sh
@Djelibeybi please review and merge

Fix typos and formatting in agentManagment.sh

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

oig agent lcm : add volume validation in status cmd

oig agent lcm : add volume validation in status cmd

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

OIG: fix error message on setupConfig

OIG: fix error message on setupConfig

---

OracleGoldenGate/21c/bin/deployment-init.py

Fix typo from commit 29e51ce378b8af0e85cd7b64cf7f407ad78b0b4a

---

OracleManagementAgent/README.md
OracleManagementAgent/dockerfiles/latest/Dockerfile

update documentation and locale settings

---

.github/workflows/build-and-push-oci-cli-image.yml

Also generate appropriate labels and tags automatically.

Rebuild the OCI CLI every week pick up the latest version

---

OracleCloudInfrastructure/oci-cli/README.md

Updated README.md  to add a section explaining how to access local files from OCI container.

Update README.md to explain local folder mapping

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8
OracleJava/8/Dockerfile
OracleJava/8/Dockerfile.8
OracleOpenJDK/18/Dockerfile

updated files to use the Jul 2022 CPU releases

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8
OracleOpenJDK/18/Dockerfile

Updated scripts to content of Java SE August Patch Update

---

OracleWebCenterPortal/dockerfiles/12.2.1.4/README.md
OracleWebCenterPortal/dockerfiles/12.2.1.4/container-scripts/configureNodeManager.py
OracleWebCenterPortal/dockerfiles/12.2.1.4/container-scripts/installElasticsearchAndStart.sh

…f Elasticsearch 7.
Signed-off-by: Anand Sirasagi <anand.sirasagi@oracle.com>

WCP-32741:- Update build scripts to support Elasticsearch

---

OracleJava/19/Dockerfile
OracleJava/19/build.sh
OracleJava/README.md
OracleOpenJDK/19/Dockerfile
OracleOpenJDK/19/build.sh
OracleOpenJDK/README.md

updated release version from JDK/OpenJDK 18 to 19

---

.github/workflows/markdown-linter.yml
.github/workflows/shellscript-linter.yml

Add GitHub Actions to lint Markdown files and shell scripts

---

OracleWebLogic/dockerfiles/14.1.1.0/README.md

Sorry if this PR is too silly. I noticed the link to the blog was broken, so I fixed it.

Fixed Weblogic Blog Link in the README

---

.github/workflows/build-and-push-dev-images.yml

I have no idea if this is correct, I just removed all mention of the compat image. If it's not correct, feel free to close this PR and submit another one.

Remove the compat image from the build workflow

---

OracleTuxedo/core/README.md
README.md

Fix Tuxedo-related URLs

---

OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Simple version bump, and some overdue name changes in comments.

Update for Instant Client 19.17

---

.github/workflows/build-and-push-dev-images.yml
.github/workflows/build-and-push-instantclient-images.yml
.github/workflows/build-and-push-nosql-image.yml

Updates for the Instant Client workflow to remove deprecation warnings.
I also updated the checkout action in other workflows per request of @Djelibeybi.  He will do the output updates in non- Instant Client actions later.

Update workflow actions to remove deprecation warnings.

---

.github/workflows/build-and-push-instantclient-images.yml

Fix repo owner name syntax

---

OracleManagementAgent/dockerfiles/latest/container-scripts/common.sh
OracleManagementAgent/dockerfiles/latest/container-scripts/install_zip.sh
OracleManagementAgent/dockerfiles/latest/container-scripts/watchdog.sh

load env var agent java options from java.options

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

Minor change in LCM script to make it compatible with latest podman versions (4.2.0 +)

Updated to support podman 4.2.0

---

.github/workflows/build-and-push-nosql-image.yml
.github/workflows/build-and-push-nosql-sec-image.yml
NoSQL/ce-sec/Dockerfile
NoSQL/ce-sec/sec/setup-http-proxy-sec.sh
NoSQL/ce/Dockerfile
NoSQL/ce/start-kvlite.sh

I have executed the script `lint` provided in PR 2513 (improve the code quality linters)
- I resolved the issues detected in `NoSQL` directory
- I resolved the issues detected in `.github/workflows/build-and-push-nosql-*`. FI: There are other files in this directory with warnings.
I have also resolved the following warnings in GitHub Workflows
- Node.js 12 actions are deprecated (`actions/checkout@v2`)
- `set-output` command is deprecated and will be disabled soon
I have fixed an issue in `setup-http-proxy-sec.sh`
- I was generating the `driver-trust` with a wrong password

Oracle NoSQL: Resolve the issues raised by the code quality linters.

---

OracleDatabase/SingleInstance/FAQ.md

This is my bit for https://github.com/oracle/docker-images/issues/2210#issuecomment-1334842940

Give Thin python-oracledb OOB syntax.  Fix grammar

---

OracleLinuxDevelopers/README.md
OracleLinuxDevelopers/oraclelinux8/nodejs/18/Dockerfile

Add Node.js 18 container image and update docs

---

.github/workflows/build-and-push-dev-images.yml

Update developer image workflow with new GitHub requirements

---

CODEOWNERS

Remove @totalamateurhour from CODEOWNERS and clean up formatting

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8
OracleJava/11/build.sh
OracleJava/17/Dockerfile
OracleJava/17/build.sh
OracleJava/19/Dockerfile
OracleJava/19/build.sh
OracleJava/8/Dockerfile
OracleJava/8/Dockerfile.8
OracleJava/8/build.sh
OracleOpenJDK/19/Dockerfile
OracleOpenJDK/19/build.sh

updated files with the entries for the Jan 2023 CPU

---

.github/workflows/build-and-push-oci-cli-image.yml

Update OCI CLI workflow to use GITHUB_OUTPUT

---

OracleInstantClient/README.md
OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Update for Instant Client 19.18

Update for Instant Client 19.18

---

OracleCloudInfrastructure/oci-cli/Dockerfile

feat: add jq to the OCI CLI container image

---

OracleRestDataServices/README.md

changed url for a broken link.

Fixed broken link: Issue : 2537

---

.github/workflows/build-and-push-nosql-image.yml
.github/workflows/build-and-push-nosql-sec-image.yml
NoSQL/README-sec.md
NoSQL/README.md
NoSQL/ce-sec/Dockerfile
NoSQL/ce/Dockerfile

NoSQL image - Improvements
- support ARM architectures
- use open source image GraalVM - replace openjdk:17-oraclelinux8

NoSQL image - Improvements

---

OracleJava/19/build.sh
OracleJava/20/Dockerfile
OracleJava/20/build.sh
OracleJava/README.md
OracleOpenJDK/19/build.sh
OracleOpenJDK/20/Dockerfile
OracleOpenJDK/20/build.sh
OracleOpenJDK/README.md

JDK 20 released on 2023-03-21.  These change updates the dockerfiles accordingly.

replaced JDK and OpenJDK 19 with 20

---

OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh

Preventing undesired exit on failure to remove dangling images in buildContainerImage.sh file

Preventing undesired exit on failure to remove dangling images

---

OracleLinuxDevelopers/oraclelinux9/gcc-toolset/12-toolchain/Dockerfile
OracleLinuxDevelopers/oraclelinux9/gcc-toolset/12-toolchain/entrypoint.sh
OracleLinuxDevelopers/oraclelinux9/golang/1.18/Dockerfile
OracleLinuxDevelopers/oraclelinux9/nginx/1.20-core/Dockerfile
OracleLinuxDevelopers/oraclelinux9/nginx/1.20-full/Dockerfile
OracleLinuxDevelopers/oraclelinux9/nginx/1.20/Dockerfile
OracleLinuxDevelopers/oraclelinux9/nodejs/16/Dockerfile
OracleLinuxDevelopers/oraclelinux9/nodejs/18/Dockerfile
OracleLinuxDevelopers/oraclelinux9/python/3.9/Dockerfile
OracleLinuxDevelopers/oraclelinux9/redis/6/Dockerfile
OracleLinuxDevelopers/oraclelinux9/ruby/3.0/Dockerfile
OracleLinuxDevelopers/oraclelinux9/ruby/3.1/Dockerfile

I've only done basic sanity testing of each image, so any additional testing is welcome. PHP has been intentially omitted.

Initial commit of Oracle Linux 9 based developer images

---

.github/workflows/build-and-push-dev-images.yml

OL9 dev images are building fine under my own account
--

ci: Update action for OL9 dev images

---

CODEOWNERS
OracleAccessManagement/dockerfiles/12.2.1.4.0/Dockerfile
OracleAccessManagement/imagetool/12.2.1.4.0/additionalBuildCmds.txt
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/Dockerfile
OracleIdentityGovernance/dockerfiles/12.2.1.4.0/container-scripts/createDomainAndStart.sh
OracleIdentityGovernance/imagetool/12.2.1.4.0/additionalBuildCmds.txt
OracleUnifiedDirectory/dockerfiles/12.2.1.4.0/Dockerfile
OracleUnifiedDirectory/dockerfiles/12.2.1.4.0/container-scripts/common_functions.sh
OracleUnifiedDirectory/dockerfiles/12.2.1.4.0/container-scripts/createAndStartOUDInstance.sh
OracleUnifiedDirectory/dockerfiles/12.2.1.4.0/container-scripts/setEnvVars.sh
OracleUnifiedDirectory/dockerfiles/12.2.1.4.0/container-scripts/startOUDInstance.sh
OracleUnifiedDirectory/imagetool/12.2.1.4.0/additionalBuildCmds.txt
OracleUnifiedDirectorySM/dockerfiles/12.2.1.4.0/Dockerfile
OracleUnifiedDirectorySM/imagetool/12.2.1.4.0/additionalBuildCmds.txt

Main idm 23.2.1 release

---

OracleDatabase/SingleInstance/FAQ.md

Added steps to run oracle database 23c free on Mac M1 chip in FAQ.md

Added steps to run oracle database 23c free on Mac M1 chip in FAQ.md

---

OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
OracleDatabase/SingleInstance/dockerfiles/19.3.0/setupLinuxEnv.sh

Fixed 2 issues in arm64 19c sidb:
1. hostname not found
2. added check to prevent user from running container with standard edition parameter on arm64 platforms

Fixed 2 issues/bugs in arm 19c sidb

---

OracleJava/21/Dockerfile
OracleJava/21/build.sh
OracleJava/README.md
OracleOpenJDK/21/Dockerfile
OracleOpenJDK/21/build.sh
OracleOpenJDK/README.md

Change JDK 20 to JDK 21 in Oracle JDK  and OpenJDK

Changed from JDK 20 to JDK 21 for both, Oracle JDK and OpenJDK

---

OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/buildContainerImage.sh

fix for https://github.com/oracle/docker-images/issues/2656

---

OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Update Instant Client to 19.21

Update Instant Client to 19.21

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8
OracleJava/8/jdk/Dockerfile
OracleJava/8/jdk/Dockerfile.8
OracleJava/8/serverjre/Dockerfile
OracleJava/8/serverjre/Dockerfile.8
OracleOpenJDK/21/Dockerfile

The new checksums and downloads correspond to 21.0.2, 17.0.10, 11.0.22, and 8u401

updated checksums and download references to the Jan 2024 CPU 

---

OracleGoldenGate/21c/bin/deployment-init.py

- In version 23c, the Service Manager is a first-class service. Instead of modifying internal data files, use the REST API to adjust the network settings for Service Manager.

Oracle GoldenGate 23c

---

NoSQL/README-sec.md
NoSQL/README.md
NoSQL/ce-sec/Dockerfile
NoSQL/ce/Dockerfile

This PR updates the Oracle NoSQL Dockerfile to align with the latest version and bundles.
`   Our last bundle for this version is kv-ce-23.3.30.`

NOSQL - Update to version 23.3.30

---

.github/workflows/build-and-push-instantclient-images.yml
OracleInstantClient/README.md
OracleInstantClient/oraclelinux9/19/Dockerfile

Add Instant Client 19 for OL9
@Djelibeybi I know you hate closed & recreated PR's - but "the system did it".

Add Instant Client 19 for OL9

---

OracleInstantClient/oraclelinux7/19/Dockerfile
OracleInstantClient/oraclelinux8/19/Dockerfile

Bump the 19c Instant Client to 19.22

Bump Instant Client to 19.22

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

@rishiagarwal-oracle Please review.

removed 777 perm

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

@rishiagarwal-oracle Please review this.

fixed image removal command

---

OracleIdentityGovernance/samples/scripts/agentManagement.sh

@rishiagarwal-oracle Please review

handled agent kill in post upgrade stage

---

OracleIdentityGovernance/samples/scripts/agentAutoUpdate.sh

@rishiagarwal-oracle Please review.

added check to prevent config override if not present

---

.github/workflows/build-and-push-instantclient-images.yml
OracleInstantClient/README.md
OracleInstantClient/oraclelinux8/23/Dockerfile
OracleInstantClient/oraclelinux9/23/Dockerfile

Initial Instant Client 23ai container push

Instant Client 23ai containers

---

.github/workflows/build-and-push-instantclient-images.yml

Fix Instant Client workflow review comment to not build 23ai on OL7.

Fix Instant Client workflow review comment

---

OracleJava/11/Dockerfile
OracleJava/11/Dockerfile.8
OracleJava/8/jdk/Dockerfile
OracleJava/8/jdk/Dockerfile.8
OracleJava/8/serverjre/Dockerfile
OracleJava/8/serverjre/Dockerfile.8
OracleOpenJDK/22/Dockerfile

Updated dockerfiles to use the Jul 2024 Critical Patch Update releases

updated files for Jul 2024 Java SE Critical Patch Updates

---

OracleLinuxDevelopers/oraclelinux8/python/3.9-oracledb/Dockerfile

Everyone uses Oracle Database, right?

Add Python 3.9 image with python-oracledb

---

OracleLinuxDevelopers/oraclelinux8/python/3.11-oracledb/Dockerfile

Add an image with Python 3.11 and python-oracledb

Add an image with Python 3.11 and python-oracledb

---

CODEOWNERS

Update the codeowners for OracleGoldenGate

Update the CODEOWNERS for GoldenGate

---

CODEOWNERS

Hand over OracleDatabase to Yunus
