- OracleWebLogic/dockerfiles/buildDockerImage.sh
In OracleWebLogic/dockerfiles/buildDockerImage.sh the $? check was looking at the return code of "rm -f Dockerfile" not "docker build". I've moved the check up. 
A failed build should now halt script execution.
> Moved exit code check up to docker build command

- OpenJDK/java-6/Dockerfile
- OpenJDK/java-7/Dockerfile
- OpenJDK/java-8/Dockerfile
- OracleJDK/java-7/Dockerfile
- OracleJDK/java-8/Dockerfile
Use the official Oracle Linux (/_/oraclelinux) images which are updated more quickly.
> Switch all FROM references to oraclelinux:latest

- OracleWebLogic/workshop/README.md
Just correct a small typo in requirements section.
Removed end line blank spaces in Weblogic section.
Corrected the Java section command/output order.
Added a dot to correct the phrase in 'Domain samples' paragraph.
> Correct README.md typo

- OracleDatabase/dockerfiles/buildDockerImage.sh
Issue #137 was caused by missing passwords. Not all operating systems, where `buildDockerImage.sh` is executed, have `pwmake` utility. Test its result before continuing
> Issue oracle/docker-images#137. Test if pwmake is present

- OracleDatabase/dockerfiles/12.1.0.2/Dockerfile.ee
- OracleDatabase/dockerfiles/12.1.0.2/Dockerfile.se2
I get the following error when trying to run the container as is:
database_1 | /bin/sh: /opt/oracle/runOracle.sh: Permission denied
Making the script executable fixes the problem.
> Make runOracle.sh executable

- OracleHTTPServer/README.md
- OracleHTTPServer/samples/1221-ohs-domain/README.md
- OracleHTTPServer/samples/1221-ohs-domain/container-scripts/configureWLSProxyPlugin-WLSMultihost.sh
- OracleHTTPServer/samples/1221-ohs-domain/container-scripts/mod_wl_ohs.conf.sample
Now user can provide custom Oracle Weblogic Proxy Plugin file containing directives as per their weblogic environments .
This file will need to be placed in docker data volume , which in turn will be mounted during OHS container creation.
In this way, the same OHS docker solution can be used to route applications running on either  Weblogic Admin Server or Weblogic cluster or set of individual Managed Servers .
> Enhancement : OHS Docker Solution with Docker Data Volume

- OracleHTTPServer/README.md
- OracleHTTPServer/samples/1221-ohs-domain/Dockerfile
- OracleHTTPServer/samples/1221-ohs-domain/README.md
- OracleHTTPServer/samples/1221-ohs-domain/container-scripts/configureWLSProxyPlugin-WLSMultihost.sh
- OracleHTTPServer/samples/1221-ohs-domain/container-scripts/configureWLSProxyPlugin.sh
- OracleHTTPServer/samples/1221-ohs-domain/container-scripts/mod_wl_ohs.conf.sample
- OracleHTTPServer/samples/1221-ohs-domain/container-scripts/startNMandOHS.sh
Readme Enhancements for better formatting and readability
Default script Change to enable stop/start of running/exited containers
> Readme Enhancements and Default script Change

- OracleWebLogic/samples/1221-medrec/startSample.sh
Added check to the start script to ensures that the domain is only created the first time the container is started. On subsequent restarts, only derby and the admin server is started. Thus retaining local changes.
> Fix to not recreate domain on container restart

- OracleDatabase/dockerfiles/12.1.0.2/runOracle.sh
While our Oracle docker images already address clean shutdown on docker stop signals, it does not address control-c yet, which is IMHO the easiest way to stop a container when experimenting in interactive mode.
> add SIGINT handler to close DB properly on control-c

- OracleDatabase/dockerfiles/12.1.0.2/runOracle.sh
Bash test cannot handle the maximum integer value of
18446744073709551615 in a 64 bit system. Introduced another check to
don’t bother if the digits of memory available go over the single digit
GB range.
> Fix for issue #219

- OracleDatabase/dockerfiles/12.1.0.2/createDB.sh
If dbca failed the dbca-log should be displayed, but the specified path is wrong. I triggered this error by using an SID with invalid character.
> fix wrong log path

- README.md
Update the README to include a link to the Oracle Container Registry.
> Add a link to Oracle Container Registry

- ContainerCloud/stacks/haproxy-lb-to-apache/Makefile
- ContainerCloud/stacks/haproxy-lb-to-nginx/Makefile
- ContainerCloud/stacks/nginx-lb-to-apache/Makefile
- ContainerCloud/stacks/nginx-lb-to-nginx/Makefile
The make files in for the load balancer stacks are missing their base container images. This PR fixes that specific issue so that all container cloud stacks are buildable.
> Fix container cloud stacks

- OracleDatabase/README.md
- OracleDatabase/dockerfiles/12.1.0.2/createDB.sh
- OracleDatabase/dockerfiles/12.1.0.2/dbca.rsp.tmpl
- OracleDatabase/dockerfiles/12.1.0.2/runOracle.sh
I'd kindly propose the following change:
* Introduce `ORACLE_CHARACTERSET` defaulted to AL32UTF8
* Change the dbca template to have a place holder for CHARACTERSET instead of the fix value above
* Use an env variable to determine the characterset for the database
Thus, the character set can be passed to the container on the first run to create a database with a different characterset for Standard Edition 2 and Enterprise Edition.
I have updated the README accordingly and hope this is of use to you too.
> Database: Provide a env variable to set the character set during db creation

- OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic
Same change as in commit ed8015d14e09369ff1dfcefee43fe52ad9d49604 - fixes missing `su` issue when using `oraclelinux:7-slim` linux
> Update Dockerfile.generic (fixing missing su)

- NoSQL/4.3.11/Dockerfile
- NoSQL/README.md
Oracle NoSQL Database 4.3 (Community Edition) is now released. It would be useful to have the Dockerfile included in this repo for the latest version. Some of the key changes from docker perspective include -
The community edition is now licensed under Apache License v2.0
oracle nosql database is now secure by default. This affects how the kvlite instance can be started within the container.
I created a patch to add the Dockerfile with necessary changes to the Readme and added the Dockerfile. Please review and let me know your feedback.
> Update NoSQL Dockerfile to use CE_4.3 #298

- .gitignore
- OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/createAndStartEmptyDomain.sh
On starting the 12.2.1.2 container, below error is logged:
`cat: date: No such file or directory`
Then the calculated admin password will always be `d41d8cd9`.
> Fix bug in createAndStartEmptyDomain.sh

- NoSQL/sample-cluster/inner-scripts/Dockerfile
- OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe
- OracleDatabase/dockerfiles/12.1.0.2/Dockerfile.ee
- OracleDatabase/dockerfiles/12.1.0.2/Dockerfile.se2
- OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.ee
- OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.se2
As written, this ends up keeping a `/bin/sh` process resident as PID 1, which can cause issues with signals being sent to the service, but mostly is unnecessary. :+1: :heart:
In case you aren't familiar with `exec`, here's the relevant docs from Bash: (https://www.gnu.org/software/bash/manual/bashref.html#index-exec)
> If command is supplied, it replaces the shell without creating a new process. ... If command cannot be executed for some reason, a non-interactive shell exits, unless the execfail shell option is enabled. In that case, it returns failure. ...
Happy to edit, rebase, adjust, etc as desired!
> Use "exec" where possible to avoid excess shell processes

- GlassFish/4.1.2/Dockerfile
- GlassFish/4.1.2/docker-entrypoint.sh
user provided password -
docker run -ti -e ADMIN_PASSWORD=<your-secret-password> -p 4848:4848 -p 8080:8080 -d oracle/glassfish:4.1.2
Auto Generated password -
docker run -ti -p 4848:4848 -p 8080:8080 -d oracle/glassfish:4.1.2
password = `docker logs <CONTAINER> | grep "GENERATED ADMIN PASSWORD"`
> Auto generated and user provided password for Glassfish 4.1.2 image

- GlassFish/4.1.1-web/Dockerfile
- GlassFish/4.1.1-web/docker-entrypoint.sh
- GlassFish/4.1.1/Dockerfile
- GlassFish/4.1.1/docker-entrypoint.sh
- GlassFish/4.1.2-web/Dockerfile
- GlassFish/4.1.2-web/docker-entrypoint.sh
- GlassFish/4.1.2/Dockerfile
- GlassFish/4.1.2/docker-entrypoint.sh
1. Auto generated and user provided password for Glassfish 4.1.2-web 4.1.1 and 4.1.1-web image
2.Updated 4.1.1 m 4.1.1-web 4.1.2-web to use jdk 1.7 as recommended jdk for glassfish 4.*.* is 1.7
> Auto generated and user provided password for Glassfish 4.1.2-web 4.1.1 and 4.1.1-web image

- OracleDatabase/README.md
- OracleDatabase/dockerfiles/11.2.0.2/runOracle.sh
- OracleDatabase/dockerfiles/12.1.0.2/createDB.sh
- OracleDatabase/dockerfiles/12.1.0.2/runOracle.sh
- OracleDatabase/dockerfiles/12.2.0.1/createDB.sh
- OracleDatabase/dockerfiles/12.2.0.1/runOracle.sh
The Docker images now support user defined passwords. If a user wants to specify a password the images will automatically pick it up via the environment variable `ORACLE_PWD`. By default, the password is still auto generated and this is the preferred secure method. That is, create the container with an auto generated password and reset the password once the container is running.
This change also makes extending the image easier by being able to pass on a password which is used by the upper stack.
> Allow for user defined passwords while still generating by default

- OracleCoherence/README.md
- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.0.0/extend-cache-config.xml
- OracleCoherence/dockerfiles/12.2.1.0.0/start.sh
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.2.0/extend-cache-config.xml
- OracleCoherence/dockerfiles/12.2.1.2.0/install.file
- OracleCoherence/dockerfiles/12.2.1.2.0/oraInst.loc
- OracleCoherence/dockerfiles/12.2.1.2.0/start.sh
- OracleCoherence/dockerfiles/buildDockerImage.sh
- OracleCoherence/docs/00.imageusage/README.md
- OracleCoherence/docs/README.md
These changes contain amendments to the Coherence images so that they contain a shell script entry point to make them runnable. Alongside this are corresponding changes to the documentation.
> Amend Coherence images to make them runnable

- OracleTuxedo/samples/mp/Dockerfile
The Dockerfile for the MP sample incorrectly uses the simpapp_runme.sh instead of the simpappmp_runme.sh
> Use the proper runme for MP sample

- OpenJDK/java-6/Dockerfile
- OpenJDK/java-7/Dockerfile
- OpenJDK/java-8/Dockerfile
This switches OpenJDK to use the `7-slim` base image and does a `yum clean` instead of a hard `rm`.
> Updating OpenJDK images 

- OracleJava/README.md
7u80 is several years old and is no longer maintained.  It is missing many security vulnerability fixes.  The download page that this document referred to clearly states this should not be used in product.
> Removed references to Server JRE 7u80

- OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.developer
- OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.generic
- OracleWebLogic/dockerfiles/12.2.1.2/Dockerfile.infrastructure
- OracleWebLogic/dockerfiles/12.2.1.2/README.md
- OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/create-wls-domain.py
- OracleWebLogic/dockerfiles/12.2.1.2/container-scripts/createAndStartEmptyDomain.sh
Allow for user to define environment variables at runtime for the WebLogic Domain creation:
DOMAIN_NAME
DOMAIN_HOME
ADMIN_NAME
ADMIN_USERNAME
ADMIN_PASSWORD
ADMIN_PORT
> Allow for user to define environment variables at runtime 

- OracleWebLogic/samples/12212-domain/Dockerfile
This patch intends to fix the following failure while building image:
"/bin/sh: /u01/oracle/wlst: Permission denied"
Signed-off-by: Dong Zhu <dong.zhu@oracle.com>
> 12212-domain: Fix the permission issue while building image

- OracleInstantClient/README.md
- OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile
This PR merges the Oracle Instant Client Dockerfile as used on the Oracle Container Registry and Docker Store.
Resolves #464.
> Add Oracle Instant Client image

- OracleFMWInfrastructure/README.md
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/Checksum
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/Dockerfile
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/container-scripts/createInfraDomainAndStartAdmin.sh
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/container-scripts/update_listenaddress.py
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/fmw_12.2.1.2.0_infrastructure_Disk1_1of1.zip.download
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/install.file
- OracleFMWInfrastructure/dockerfiles/12.2.1.2/oraInst.loc
- OracleFMWInfrastructure/dockerfiles/buildDockerImage.sh
The Oracle FMW Infrastructure image now installs the binaries using the FMW Infrastructure 12.2.1.2 installer and has the scripts to build a base JRF enabled domain with an Admin Server and Managed Server.
> Changes to the FMW Infrastructire 12.2.1.2  Image

- CONTRIBUTING.md
Added details to the CONTRIBUTING.md guide about requiring a signed OCA and how to sign off git commits.
> Add OCA details and sign-off requirements.

- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.standalone
Got the following error while running the Coherence container:
"sh: /start.sh: Permission denied"
This patch intends to fix it.
Signed-off-by: Dong Zhu <dong.zhu@oracle.com>
> OracleCoherence: Fix the permission issue while running the container

- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.standalone
Apart from being in breach of the contribution rules, these passwords are not actually required. I built and tested the images locally without them and everything worked.
> Fixes issue #502 - Remove oracle user password in Coherence Dockerfiles

- OracleSOASuite/dockerfiles/12.2.1.2-soabpm/Dockerfile
Switch `middleware` to `oracle` in the FROM directive to match the documentation of the upstream image.
Signed-off by: Avi Miller <avi.miller@oracle.com>
> Correct the FROM directive

- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.standalone
Got the following warning while building the image:
"useradd: warning: the home directory already exists.
Not copying any file from skel directory into it."
This patch intends to fix it.
Signed-off-by: Dong Zhu <dong.zhu@oracle.com>
> OracleCoherence: Fix warnings while building image

- OracleDatabase/dockerfiles/12.1.0.2/checkSpace.sh
- OracleDatabase/dockerfiles/12.1.0.2/installDBBinaries.sh
- OracleDatabase/dockerfiles/12.2.0.1/checkSpace.sh
- OracleDatabase/dockerfiles/12.2.0.1/installDBBinaries.sh
The bulk of these changes save 430+MB of both, 12.2.0.1 and 12.1.0.2 images.
There is also one correction of the required space in 12.1.0.2 in `checkSpace.sh` where the required space is only 12GB rather than 15GB for 12.2.
> Make DB image smaller, correct checkSpace.sh for 12.1.0.2

- NoSQL/4.5.12/Dockerfile
- NoSQL/README.md
Oracle NoSQL Enterprise Edition v4.5 was released earlier this week. Adding a Dockerfile to build a docker image for that version.
> Add NoSQL EE 4.5 Dockerfile and README update

- OracleGoldenGate/Dockerfile
- OracleGoldenGate/README.md
- Re-arrange comments in Dockerfile to fix "[WARNING]: Empty continuation lines will become errors in a future release." reported in Docker version 17.07.0-ce
- Change link for Oracle GoldenGate documentation to the current release, 12.3.0.1.0
> Oracle GoldenGate on Docker

- OracleWebLogic/dockerfiles/12.2.1.3/README.md
Changed "Newwork" to "Network", so the line:
docker inspect --format '{{.NewworkSettings.IPAddress}}' <container-name>
is now:
docker inspect --format '{{.NetworkSettings.IPAddress}}' <container-name>
> Fixed a typo in a docker command in README.md

- OracleWebLogic/dockerfiles/12.2.1.3/README.md
Changed "8001" to "7001" as it is inconsistent with rest of instructions, so the line:
This returns the IPAddress (example xxx.xx.x.x) of the container.  Got to your browser and enter http://xxx.xx.x.x:8001/console
is now:
This returns the IPAddress (example xxx.xx.x.x) of the container.  Got to your browser and enter http://xxx.xx.x.x:7001/console
> Fixed a typo in admin console URL in README.md

- OracleJava/README.md
A blog with more information on the server JRE is now a better source of information on what that package option is  and why it is being offered.
> Better location for information on server JRE

- OracleGoldenGate/Dockerfile
- OracleTuxedo/core/dockerfiles/12.1.3/Dockerfile
- OracleTuxedo/core/dockerfiles/12.2.2/Dockerfile
* Replacing yum -y clean all with rm -rf /var/cache/yum to avoid the annoying yum message that now appears.
> Replacing yum -y clean all across the repo

- OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe
Oracle XE 11.2.0.2 RPM runs into issues on newer Oracle Linux caused by elevated kernel defaults and insufficient container swap. This PR forges these values just for the duration of rpm install, resulting in clean image build.
> Forge /proc and free for successful XE 11.2.0.2 install

- OracleCloudInfrastructure/README.md
- OracleCloudInfrastructure/terraform-oci/Dockerfile
- OracleCloudInfrastructure/terraform-oci/README.md
This is a simple `Dockerfile` inspired by Lucas Gomes' article to build a Docker container that embeds Terraform and the OCI Provider.
Inspiration: https://medium.com/oracledevs/containerized-terraform-for-oci-provider-2deb917783fa
> Adding a Terraform with OCI Provider image.

- CODEOWNERS
As @brunoborges has decided to venture off on a new adventure, we'll have to somehow manage without him. 
> Remove Bruno from the list of code owners.

- OracleCloudInfrastructure/terraform-oci/Dockerfile
- OracleCloudInfrastructure/terraform-oci/README.md
Minor change to the `Dockerfile` so that it builds using the latest available version of both Terraform and the OCI Provider. This means I don't have to keep updating the Dockerfile every time we release a new version of each.
> Updating the Dockerfile to install the latest versions 

- OracleDatabase/README.md
Enterprise and Standard Edition 2 uses ``/opt/oracle/scripts/``.  
Express Edition uses ``/u01/app/oracle/scripts``.  
To clear specification, ``Add note to under Running scripts after setup and on startup`` section.
> Add note to README.md for Express Edition.

- OracleDatabase/dockerfiles/11.2.0.2/checkDBStatus.sh
This fixes the bug with the database status check for XE raised in #756.
> Bugfix for XE database statuscheck

- CODEOWNERS
Replace old GitHub user with new one.
> Update new codeowner github user

- NoSQL/4.5.12/README.md
This will override the global README.md being used as the full description when triggering an Automated Build on Docker Hub.
> Adding a specific README.md in the same location as the Dockerfile

- OracleWebLogic/samples/12213-webtier-apache/README.md
Remove the environment options in the volume mount examples. They are not needed because user's own plugin config may not have those.  They do not cause any problem, but may cause confusion.
Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>
> Clean up README.md

- OracleCloudInfrastructure/terraform-oci/LICENSE
- OracleCloudInfrastructure/terraform-oci/README.md
> Change from UPL to Public Domain dedication.

- CONTRIBUTING.md
This makes it clear that images must use `oraclelinux:7-slim` when a more specific product image is not applicable. 
The `7-slim` variant has the smallest attack surface because it has the least amount of packages installed and is updated whenever a CVE patch is released for any package within the image.
> Update contribution guide 

- OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/Dockerfile.xe
Bugfix for #858: Don't run health check shell as `oracle` as it's already taken care of inside the script.
> Don't run check script via su

- OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/runOracle.sh
Merge save/restore handling from runOracle.sh 12.2.0.1
OracleDatabase/SingleInstance/11.2.0.2/xe does not start proper due missing /etc/oratab file on second container start.
Merge of lines:
https://github.com/oracle/docker-images/blob/dae5e50be1b651c14c2a680cc5ea56ca8d08993f/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh#L27
https://github.com/oracle/docker-images/blob/dae5e50be1b651c14c2a680cc5ea56ca8d08993f/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh#L56
> fix(OracleDatabase): add save/restore oratab to runOracle.sh

- OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile.developer
- OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile.generic
- OracleWebLogic/dockerfiles/12.2.1.3/README.md
- OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/create-wls-domain.py
- OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/createAndStartEmptyDomain.sh
Changes to secure Admin username/password
@rosemarymarano @Djelibeybi @TheFrogPad
> Changes to secure Admin Authentication 

- OracleWebLogic/dockerfiles/12.2.1.3/README.md
Correct typo in README, and add description to clarify the directory where the properties file needs to be mapped to
> Correct typo and add clarification in instructions

- OracleWebLogic/samples/12211-patch/Dockerfile
- OracleWebLogic/samples/12211-patch/README.md
Remove invalid option - oracle from OPatch command.
Add to README instructions to verify that a patch has been applied correctly.
> Correct OPatch command and Provide instruction to verify patch has been applied

- OracleWebLogic/dockerfiles/12.2.1.3/README.md
And, the link under "Choose your Oracle WebLogic Server distribution," For more information on the Oracle WebLogic Server 12cR2 Quick Install Developer Distribution, see **WLS Quick Install Distribution for Oracle WebLogic Server 12.2.1.3.0**, does not work.
> minor typos

- OracleWebLogic/dockerfiles/12.2.1.3/README.md
- OracleWebLogic/samples/12213-patch/Dockerfile
- OracleWebLogic/samples/12213-patch/README.md
- OracleWebLogic/samples/12213-patch/p27117282_122130_Generic.download
Add note to the README that asks user to apply  patch to the install image of WebLogic if the Administration port is enabled.  
Add WebLogic 12.2.1.3 patching sample.
This resolves issue #923.
> Note to apply  patch if the Administration port is enabled.  

- OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/18.3.0/runOracle.sh
- OracleDatabase/SingleInstance/tests/runContainerTests121.sh
- OracleDatabase/SingleInstance/tests/runContainerTests122.sh
- OracleDatabase/SingleInstance/tests/runContainerTests183.sh
> Make ORACLE_SID and ORACLE_PDB always uppercase

- GraalVM/CE/1.0.0-rc7/Dockerfile
- GraalVM/CE/1.0.0-rc7/gu-wrapper.sh
The wrapper takes care that alternative links in /usr/bin are updated when new components are installed or uninstalled.
This simplifies derived Docker images.
> Adding wrapper for graal-updater

- CODEOWNERS
- OracleInstantClient/README.md
- OracleInstantClient/dockerfiles/18.3.0/Dockerfile
I updated the `Dockerfile` to automatically configure the `ol7_oracle_instantclient` repo and then install RPMs directly from the [Oracle Linux yum server](https://yum.oracle.com). I also updated the `README.md` file accordingly.
> Updating the 18.3 Instant Client 

- OracleInstantClient/README.md
Add the missing 'current directory' argument to `docker build`.
> Correct the Instant Client 18.3 build syntax

- OracleWebLogic/samples/12213-domain-home-in-image/Dockerfile
- OracleWebLogic/samples/12213-domain-home-in-image/README.md
- OracleWebLogic/samples/12213-domain-home-in-image/build.sh
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/create-wls-domain.py
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/createWLSDomain.sh
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/shutdown-servers.py
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startAdminServer.sh
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startManagedServer.sh
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/waitForAdminServer.sh
- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/wlst
- OracleWebLogic/samples/12213-domain-home-in-image/properties/domain.properties
- OracleWebLogic/samples/12213-domain-home-in-image/properties/security.properties
Create new sample, a WebLogic Server 12.2.1.3 domain with the DOMAIN_HOME inside of the Docker image.
Cluster can be Configured or Dynamic, and with a DataSource.
> Create new sample for WebLogic Domain in image

- OracleInstantClient/dockerfiles/18.3.0/Dockerfile
Remove obsolete comment from the Dockerfile
> Instant Client 18.3 doesn't need downloaded files

- OracleWebLogic/samples/12213-patch-wls-for-k8s/Dockerfile
- OracleWebLogic/samples/12213-patch-wls-for-k8s/README.md
- OracleWebLogic/samples/12213-patch-wls-for-k8s/p28076014_122130_Generic.download
- OracleWebLogic/samples/12213-patch-wls-for-k8s/p28298734_122130_Generic.download
Removed patch p27117282_122130_Generic.zip which is not required
Added patch p28298734_122130_Generic.zip which is required (it is a prereq for p28076014_122130_Generic.zip and it supersedes p27117282_122130_Generic.zip)
> Update WLS patch for k8s to have correct patches

- .gitattributes
If a configuration file is checked out by a windows machine the new line is changed to CRLF. 
The changed configuration file can corrupt the target unix image it will be used with.
Signed-off-by: Christian Louis <c.louis@mail.de>
> LF for *.conf files that are used inside of unix vm

- OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/startManagedServer.sh
in docker-images/OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/startManagedServer.sh, the domain name was hard-coded to 'InfraDomain'. When running the managed server container using:
`docker run -d -p 9801:8001 --network=InfraNET --volumes-from InfraAdminContainer --name InfraManagedContainer --env-file ./infraServer.env.list oracle/fmw-infrastructure:12.2.1.3 startManagedServer.sh`
If the domain name set in 'infraServer.env.list' is different than 'InfraDomain', the managed server fails to start.
> fix startManagedServer.sh hard-coded domain name

- OracleDatabase/SingleInstance/README.md
- Updated Oracle Database version 12c Release 1 from **12.1.0.1** to **12.1.0.2**  in OracleDatabase/SingleInstance/README.md 
Signed-off-by: Yann Toqué <toqueyann@gmail.com>
> 12.1.0.1 changed to 12.1.0.2 in README.md

- OracleWebLogic/samples/12213-domain-home-in-image-wdt/build.sh
- OracleWebLogic/samples/12213-domain-home-in-image-wdt/container-scripts/setEnv.sh
- OracleWebLogic/samples/12213-domain-home-in-image-wdt/properties/docker-build/domain.properties
1. New environment variable to specify a WDT release version to download instead of the latest release (default behavior)
2. Document the different ways to set an environment variable for the build.
2. Change the setEnv.sh to inspect the properties file for the build.sh environment variables
3. Fix checks for valid JAVA_HOME
4. Fix checks for download of valid WDT install image
5. Fix parsing of the ADDITIONAL_BUILD_ARGS and CUSTOM_BUILD_ARGS  by the setEnv.sh 
6. Fix checks for valid curl executable
> Download a specific release of WDT

- OracleDatabase/SingleInstance/dockerfiles/18.4.0/checkDBStatus.sh
The checkDBStatus is returning a 0 at the start of the initial configuration of the database 18.4.0-xe. Because of this, the docker healthcheck parameter '--start-period' has no effect.
I added a check for the file "oratab" in the data volume. This file is created at the end of the configuration. So during the configuration, the check always returns a 1 and after the configuration, the sqlplus command does the real health check.
This pull request only changed the check for the database version 18.4.0. In case this change is also valid for other versions, then copy it there too.
Regards,
Vincent
> Correct checkDBStatus during configuration

- OracleJava/README.md
- OracleJava/java-8/server-jre-8u211-linux-x64.tar.gz.download
Updated the files to point to the Apr 2019 CPU so 8u201->8u211
Added some text to the directories README file clarifying the licenses (the JDK has its own licenses on Oracle's download sites, the dockerfiles on this project under UPL), and clarified what a supported image is.
> Apr 2019 Java SE CPU

- OracleCoherence/samples/122132-patch-for-k8s/README.md
Add instructions to ensure Coherence 12.2.1.3 base Docker image is named or tagged to work with the patch Dockerfile
> Add instructions to ensure Coherence 12.2.1.3 base Docker image is named or tagged to work with the patch Dockerfile

- .github/no-response.yml
This will automatically close issues after 14 days that have the more-info-required tag attached with a message.
> Configuring the No Response bot.

- .github/wip.yml
Enables the WIP Probot that prevents merges for PRs that have "WIP" in their title.
> Adding configuration for the Work-In-Progress Probot

- OracleInstantClient/dockerfiles/18/Dockerfile
- Update for Instant Client 18.5 release
- Use just the major version to make future upgrades easier.
- Parameterize the version number
> Update for Instant Client 18.5 release

- OracleInstantClient/dockerfiles/18/Dockerfile
- OracleInstantClient/dockerfiles/19/Dockerfile
Fix for modular repo files.
Note although the IC channel is enabled by default with oracle-release-el7, the explicit `--enable` is retained to help users without modular repo files.
> Ensure the channel is available

- LICENSE
This is to ensure that GitHub correctly identifies the UPL-1.0 text.
> Updating the LICENSE formatting

- OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile
- OracleFMWInfrastructure/dockerfiles/12.2.1.3/README.md
Correct permissions on container-scripts 
Correct permissions in  /u01
Make README.md more descriptive of commands to start containers.
> Correct permissions on container-scripts and /u01

- OracleCloudInfrastructure/terraform-oci/Dockerfile
To access ol7_developer repo, must install oraclelinux-developer-release-el7 first.
> Must use Oracle Linux yum server release package

- OracleWebLogic/samples/12213-webtier-apache/Dockerfile
- OracleWebLogic/samples/12213-webtier-apache/custom_mod_cgi.conf.sample
- OracleWebLogic/samples/12213-webtier-apache/custom_mod_mpm.conf.sample
The change set the worker MPM module by default instead of prefork MPM. This is a potential fix for the related BUG 29362431.
Edited to remove internal bug reference.
> OWLS-72196 set the worker module as the default MPM module

- OracleSOASuite/dockerfiles/12.2.1.3/container-scripts/createDomainAndStart.sh
If rand_pwd echo's "INFO: ${s}", then DB_SCHEMA_PASSWORD wrongly gets value as INFO: and does not adhere to Oracle DB password requirements.
Hence rand_pwd should only echo password and not echo with INFO:.
> rand_pwd should only echo password and not INFO:

- OracleInstantClient/README.md
- OracleInstantClient/dockerfiles/19/Dockerfile
The Dockerfile is really a README for how to use Instant Client.  Showing where to put network config files is useful.
> Show the default directory for Oracle Net configuration files

- OracleFMWInfrastructure/samples/12213-domain-home-in-image/Dockerfile.rcu
- OracleFMWInfrastructure/samples/12213-domain-home-in-image/README.md
- OracleFMWInfrastructure/samples/12213-domain-home-in-image/build.sh
1- Correct Dockerfile.rcu to extend the correct image
2- Pass in one parameter to build.sh to define the network
3- Document the change to the build.sh script
> Correct image to extend, and pass in parameter to build.sh to define the network

- OracleInstantClient/README.md
- OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile
- OracleInstantClient/dockerfiles/18/Dockerfile
- OracleInstantClient/dockerfiles/19/Dockerfile
This ensures that the latest base image is used. The `docker build` command for Oracle 19c Instant Client fails when an out-of-date image for `oraclelinux:7-slim` is present.
> Add '--pull' option to `docker build` instructions

- OracleJava/java-8/Dockerfile
The pre-built Server JRE image includes the `tar` and `gzip` utilities so I'm adding this to the `Dockerfile` as well, so that manually built images do too.
> Aligning Dockerfile on GitHub with the one used for OCR & Docker Hb

- OracleFMWInfrastructure/samples/12213-domain-home-in-image/Dockerfile
- OracleFMWInfrastructure/samples/12213-domain-home-in-image/README.md
- OracleFMWInfrastructure/samples/12213-domain-home-in-image/build.sh
- OracleFMWInfrastructure/samples/12213-domain-home-in-image/build_rcu.sh
- OracleFMWInfrastructure/samples/12213-patch-fmw-for-k8s/Dockerfile
- OracleFMWInfrastructure/samples/12213-patch-fmw-for-k8s/README.md
- OracleFMWInfrastructure/samples/12213-patch-fmw-for-k8s/build.sh
- OracleFMWInfrastructure/samples/12213-patch/Dockerfile
- OracleFMWInfrastructure/samples/12213-patch/README.md
- OracleWebLogic/samples/12213-domain-home-in-image-wdt/Dockerfile
- OracleWebLogic/samples/12213-domain-home-in-image-wdt/README.md
- OracleWebLogic/samples/12213-domain-home-in-image-wdt/build.sh
- OracleWebLogic/samples/12213-domain-home-in-image-wdt/quickBuild.sh
- OracleWebLogic/samples/12213-domain-home-in-image/Dockerfile
- OracleWebLogic/samples/12213-domain-home-in-image/README.md
- OracleWebLogic/samples/12213-domain-home-in-image/build.sh
- OracleWebLogic/samples/12213-patch-wls-for-k8s/Dockerfile.patch-ontop-12213
- OracleWebLogic/samples/12213-patch-wls-for-k8s/Dockerfile.patch-ontop-12213-psu
- OracleWebLogic/samples/12213-patch-wls-for-k8s/README.md
- OracleWebLogic/samples/12213-patch-wls-for-k8s/build.sh
- OracleWebLogic/samples/12213-patch/Dockerfile
- OracleWebLogic/samples/12213-patch/README.md
WebLogic Operator team has gotten reports from other Oracle teams that the samples used to create a domain home in a docker image did not function when an OPatch was applied to on the docker image created with the domain home.
Updates to the WebLogic samples are required such that the images run as `oracle` user which then enables an OPatch to be applied on top of the domain image. File permission errors resulted without these changes to how the Dockerfiles setup directories an apply the OPatch. An additional update to the docker build flags was made so that the docker cache is not used.
> Resolve issues with the WebLogic domain-in-image samples when patches are applied on top of the domain image

- OracleWebLogic/samples/12213-coherence-domain-in-image-wdt/container-scripts/setEnv.sh
- OracleWebLogic/samples/12213-coherence-domain-in-image-wdt/container-scripts/startAdminServer.sh
- OracleWebLogic/samples/12213-coherence-domain-in-image-wdt/container-scripts/startManagedServer.sh
- OracleWebLogic/samples/12213-coherence-domain-in-image-wdt/container-scripts/waitForAdminServer.sh
The container scripts are needed to build the docker image used by the Coherence demo.
> Add container scripts needed for Coherence demo

- OracleWebLogic/samples/12213-coherence-domain-in-image-wdt/README.md
The previous command had hardcoded paths that would not work in a user's environment.  Fix this by using an ENV VAR in the docker run command.
> Use ENV VAR in docker run command for Coherence demo

- OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/startAdminServer.sh
If you add JVM arguments of type -Dkey1=value1 -D key2=value2... in JAVA_OPTIONS property of file security.properties, only the "-Dkey1" part gets captured and added as JVM arguments when starting the server. Adding the "-" to the "-f2" argument fix the problem because you get the rest of the value. This could also be applyed to password value because equals sign could be part of a password.
> Read JAVA_OPTIONS fix

- OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile
- OracleFMWInfrastructure/dockerfiles/12.2.1.4/Dockerfile
- OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile.developer
- OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile.generic
- OracleWebLogic/dockerfiles/12.2.1.3/README.md
- OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.developer
- OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.generic
- OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.slim
Fix  #1435
Do not remove *.loc file it is needed to do OPatch lsinventory
> Fixed documentation extending JRE and leave *.loc file

- CONTRIBUTING.md
Making it clear that internal users need to get approval prior to submitting a pull request and providing a contact on where to get info on that process. 
Also cleaned up the language around the code owners file.
> Updating the contribution guide 

- OracleJava/java-11/Dockerfile
- OracleJava/java-8/Dockerfile
The change reduces the final image size for JDK 11 image by 28% (637MB -> 455MB) and for the server JRE 8 by 18% (356 MB -> 290MB)
I also copied some of the style for documenting/comments used by  the weblogic images.
> Changed Dockerfiles to multistage 

- OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.developer
- OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.generic
- OracleWebLogic/dockerfiles/12.2.1.4/Dockerfile.slim
This earlier version performed an unnecessary chown on the entire /u01.  This duplicates the entire layer costing significant image size.
> Chown only specific scripts to reduce image size

- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.0.0/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.0.0/start.sh
- OracleCoherence/dockerfiles/12.2.1.2.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.2.0/start.sh
- OracleCoherence/dockerfiles/12.2.1.3.0/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.3.0/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.3.0/start.sh
- OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/Dockerfile
- OracleCoherence/dockerfiles/12.2.1.4.0/src/main/docker/start.sh
When running containers on OpenShift the images run with an arbitrary user created dynamically regardless of the user specified in any Dockerfile. Whilst it is possible to configure OpenShift to allow any user in a container and work around this restriction we do not want to force customers to have to lower the OpenShift security policies.
This change makes sure that the files added to the images are owned by the oracle user and are readable/writable by the root group. The user created by OpenShift will be in the root group and will hence be able to run the images. See: https://docs.okd.io/latest/creating_images/guidelines.html
> Amend Oracle Coherence Docker files to build images that will run on OpenShift

- GraalVM/CE/19/Dockerfile.java11
- GraalVM/CE/19/README.md
- New GraalVM CE 19.3.0.2 release
- Adding first multiarch amd64/arm64 image: `oracle/graalvm-ce:19.3.0.2-java11`
> New GraalVM CE release

- OracleJava/java-11/Dockerfile
- OracleJava/java-8/Dockerfile
Update the ServerJRE and JDK versions on the dockerfiles so 8u231 -> 8u241 and 11.0.5 -> 11.0.6
> Updated versions of the JDK and ServerJRE in the Dockerfiles to Jan CPU

- CODEOWNERS
Including myself for `OracleJava` so future PRs from @aureliogrb are automatically assigned to me for review.
> Updating CODEOWNERS for OracleJava 

- OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/18.3.0/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
Hi! I've faced with a tricky problem. Getting "ORA-12154: TNS:could not resolve the connect identifier" when trying to connect to my PDB via JDBC thin client using string "user/password@tnsname" within docker container. Meanwhile I still was able to connect via sqlplus using the same string. As I figured out later the problem was in not indented strings in tnsnames.ora. Here in  [Oracle docs](https://docs.oracle.com/cd/A57673_01/DOC/net/doc/NWUS233/apb.htm) I have found a rule "_Any keyword in a configuration file that should be recognized as beginning a parameter that includes one or more keyword-value pairs must be in the far left column of a line. If it is indented by one or more spaces, it is interpreted as a continuation of the previous line._". Look like JDBC thin client can't …
> Indentation in tnsnames.ora

- OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh
Relates to issue #1376 - 
1. If unable to test for supported Docker version, test for supported Podman version
2. If errors are encountered at any stage, exit.
For background of podman/buildah see https://docs.oracle.com/en/operating-systems/oracle-linux/8/relnotes8.0/ol8-features-container.html 
Buildah libs in Podman have had multi-stage build support for some time but improvements were made in 1.6.0 and it's as good a place to start as any. The first podman RPM shipped with OL8 included buildah libs 1.9.0 so it could be raised to that version.
I may have over-complicated it, let me know your thoughts.
> Hotfix podman support

- OracleCoherence/README.md
- OracleCoherence/dockerfiles/12.2.1.3.2/Dockerfile.quickinstall
- OracleCoherence/dockerfiles/12.2.1.3.2/Dockerfile.standalone
- OracleCoherence/dockerfiles/12.2.1.3.2/extend-cache-config.xml
- OracleCoherence/dockerfiles/12.2.1.3.2/install.file
- OracleCoherence/dockerfiles/12.2.1.3.2/oraInst.loc
- OracleCoherence/dockerfiles/12.2.1.3.2/p29204496_122130_Generic.download
- OracleCoherence/dockerfiles/12.2.1.3.2/start.sh
- OracleCoherence/dockerfiles/buildDockerImage.sh
This fix will address https://github.com/oracle/docker-images/issues/1523
The current scheme of creating 12.2.1.3.2 image by using Coherence 12.2.1.3.0 base image and then patching it with Coherence cumulative patch, bloats the size of the image. 
Creation is now handled by Dockerfiles specialized for this in a separate 12.2.1.3.2 directory and include fixes for running on OpenShift.
> Changes for creating 12.2.1.3.2 docker image that will work with OpenShift

- OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
If I build an Oracle XE Docker Image by calling
```
% ./buildDockerImage.sh -v 18.4.0 -x
```
and then run the image in interactive mode
```
% docker run -it oracle/database:18.4.0-xe /bin/bash
```
I will see that the rather large `oracle-database-xe-18c-1.0-1.x86_64.rpm` is saved in the container:
```
total 2.4G
drwx------ 2 root root 4.0K Mar 12 12:15 .
drwxrwxrwt 1 root root 4.0K Mar 12 12:35 ..
-rw-r--r-- 1 root root 2.4G Jan 21 15:53 oracle-database-xe-18c-1.0-1.x86_64.rpm
```
This PR deletes the folder `/var/tmp/yum-*`.
> Removes oracle-database-xe.rpm from Docker Image

- OracleDatabase/SingleInstance/samples/prebuiltdb/README.md
I try out readme for prebuildtbd and the described paths don't match the directory structure. I fix it.
> Paths in documentation don't match directory structure

- OracleRestDataServices/README.md
- OracleRestDataServices/dockerfiles/runOrds.sh
- OracleRestDataServices/dockerfiles/standalone.properties.tmpl
Add option to specify a different context-root using `CONTEXT_ROOT` env variable (default remains `/ords`)
Signed-off-by: Fabio Caseri
> [OracleRestDataServices] Use custom context-root if specified by CONTEXT_ROOT env variable

- CONTRIBUTING.md
- OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/Dockerfile.xe
- OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/Dockerfile.ee
- OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/Dockerfile.se2
- OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/18.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/samples/applypatch/12.1.0.2/Dockerfile.ee
- OracleDatabase/SingleInstance/samples/applypatch/12.1.0.2/Dockerfile.se2
- OracleDatabase/SingleInstance/samples/applypatch/12.2.0.1/Dockerfile.ee
- OracleDatabase/SingleInstance/samples/applypatch/12.2.0.1/Dockerfile.se2
- OracleDatabase/SingleInstance/samples/prebuiltdb/README.md
- OracleDatabase/SingleInstance/tests/runContainerTests193.sh
- OracleDatabase/SingleInstance/tests/runImageBuildTests.sh
* Remove `VOLUME` from Database images
* Remove `EXPOSE` from Database images
* Use `LABEL` for volume, expose and other information
* Update Contributing.md with `LABEL` guidelines
* Introduce 19c test case
* Change prebuilt DB image sample
@Djelibeybi, please review everything ;)
@mriccell, please review Contributing.md and an example regarding the label structure.
> Remove volume expose

- OracleJava/java-11/Dockerfile
- OracleJava/java-8/Dockerfile
Updated 8u241 to 8u251 and 11.0.6 to 11.0.7 which released as part of the April 2020.
> Updated Dockerfiles with the April 2020 CPU releases

- GraalVM/CE/Dockerfile.ol8
- GraalVM/CE/Dockerfile.ol8-java11
This PR is based on the discussion #1528 about using OL8 as base image for GraalVM-CE
Signed-off-by: Mohammed Aboullaite <aboullaite.mohammed@gmail.com>
> Add oraclelinux:8-slim as base image for GraalVM-CE

- OracleWebCenterSites/dockerfiles/12.2.1.4/install.file
This is a fix for a internally reported bug.
(Removing internal bug references)
> double quotes removed from param literal

- OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile
As of Oracle instant client 19, ldconfig is automatically run during RPM install. latest cx_Oracle 8, pulls in instant client 19 via   
Requires: libclntsh.so >= 19.1
> ldconfig no longer needed

- OracleDatabase/SingleInstance/extensions/README.md
- OracleDatabase/SingleInstance/extensions/buildExtensions.sh
- OracleDatabase/SingleInstance/extensions/patching/Dockerfile
- OracleDatabase/SingleInstance/extensions/patching/README.md
- OracleDatabase/SingleInstance/extensions/patching/patchDBBinaries.sh
- OracleDatabase/SingleInstance/extensions/patching/runDatapatch.sh
- OracleDatabase/SingleInstance/extensions/patching/runOracle.sh
- OracleDatabase/SingleInstance/extensions/patching/savePatchSummary.sh
1. Added a folder named extensions which could be used to provide additional features in docker images and the user can extend the base image to include these features.
2. Added script buildExtensions.sh which provides the user to extend the image and choose which features needs to be included in the extended image.
3. Added a folder called patching under extensions folder which provided patching support.
> Extension to support patching in 19.3 docker images

- CODEOWNERS
This is to provide a secondary approver.
> Add mark-au to the OracleLinuxDevelopers content as CODEOWNER

- OracleLinuxDevelopers/oraclelinux7/golang/1.13/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/golang/1.14/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/golang/1.15/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/nodejs/10-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/nodejs/10/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/nodejs/12/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/php/7.4-apache-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/php/7.4-apache/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/php/7.4-cli-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/php/7.4-cli/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/php/7.4-fpm-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/php/7.4-fpm/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/python/3.6/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/golang/1.13/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/nodejs/10/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/nodejs/12/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.2-apache/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.2-cli/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.2-fpm/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.3-apache/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.3-cli/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.3-fpm/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/python/3.6/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/python/3.8/Dockerfile
These labels are used by GitHub Container Registry as well as third-party registry and orchestration tools.
Also fixes a typo bug in `oraclelinux7/python/3.6-oracledb/Dockerfile`.
> Adding OpenContainer image-spec labels to OracleLinuxDeveloper images

- CONTRIBUTING.md
This would replace our previous requirements of using custom labels. The GitHub Container Registry can (and does) read `image-spec` labels as do other downstream registry and orchestration products.
> Update the CONTRIBUTING.md to use image-spec labels instead

- OracleWebLogic/samples/12213-coherence-domain-in-image-wdt/Dockerfile
Base image was changed to oracle:root, so this sample Dockerfile needed to be updated to match.
> update COH sample Dockerfile to match base image oracle:root

- .gitattributes
Added eol=lf on Checksum.* files because md5check command is sensitive to crlf endings, when runned from windows machines
> added Checksum.* on gitattributes

- OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
With podman 2.0.5 on OL8 (not tested in other configurations), the Oracle 18.4.0 XE will fail while installing `oracle-database-xe-18c-1.0-1.x86_64.rpm` with the following error message:
```
su: cannot open session: Permission denied
[SEVERE] The su command is not configured properly or the oracle user does not have the required privileges to install the Oracle database. If you are running in a Docker environment, ensure to set the environment variable ORACLE_DOCKER_INSTALL=true and try again.
```
The rpm script comment out `oracle   hard   memlock    134217728` in `/etc/security/limits.d/oracle-database-preinstall-18c.conf`, but apparently we need to also comment out `oracle   hard   nofile    65536`.
Strictly speaking it is most probably a bug in the rpm, but we can fix this in …
> Allow install of the oracle-xe-18c rpm with podman

- .github/workflows/build-and-push-dev-images.yml
This PR adds a GitHub Action to build push to GHCR the Developper container images.
Build is triggered either manually or when the action or the images source are pushed to the master branch.
Manual update allows us to trigger a re-build when the base containers or packages are updated.
--
> Build action for Developer images

- .github/workflows/build-and-push-dev-images.yml
Currently we're using a Personal Access Token to push images to
GitHub Container Registry, but we want the images to be pushed to the
right namespace.
> [fix] GHCR does not support GITHUB_TOKEN so workarounds are required

- OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile
Switch to using the new Oracle Instant Client repo by installing
the oracle-instantclient-release-el7 package and actually install
nodejs and the node-oracledb-node12 packages.
Fixes #1837.
> [bug] Fix oraclelinux7-nodejs:12-oracledb Dockerfile

- .github/workflows/build-and-push-dev-images.yml
- Only rebuild chenged images.
- Improved tagging:
- Add a datestamp to the images to avoid tagless images on update
- Tag all parts of multi-arch images (manifest and images)
> Developer images: improve build action.

- CODEOWNERS
Especially with the new GitHub Actions workflow to automatically build the images.
> [repo] Add AmedeeBulle as a code owner for OracleLinuxDevelopers

- .github/workflows/build-and-push-dev-images.yml
- OracleLinuxDevelopers/oraclelinux7/ruby/2.6/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/ruby/2.7-nodejs/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/ruby/2.7/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/ruby/2.6/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/ruby/2.6/ruby.module
- OracleLinuxDevelopers/oraclelinux8/ruby/2.7/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/ruby/2.7/ruby.module
The Oracle Linux 7 images use Ruby from the Software Collections
Library while the Oracle Linux 8 images use the Ruby module from
the AppStream repo.
All images come with both rake and gem preinstalled.
Image sizes are really nice and small:
```
oraclelinux7-ruby:2.6   157MB
oraclelinux7-ruby:2.7   158MB
oraclelinux8-ruby:2.6   136MB
oraclelinux8-ruby:2.7   137MB
```
Note that we haven't (yet) released the `rh-ruby26` and `rh-ruby27`
SCLs for `aarch64` for Oracle Linux 7 yet, so the workflow will 
skip that combination for now. Once they're released, we 
can enable the build.
If you'd like to test the images, I've made the two packages built by my 
GitHub Action test run public:
<https://github.com/users/Djelibeybi/packages/container/package/oraclelinux7-ruby> …
> [dev] Add Ruby 2.6 and 2.7 images for Oracle Linux 7 and 8

- OracleWebCenterSites/dockerfiles/12.2.1.4/wcs-wls-docker-install/Manifest.txt
This transaction consists wcs-wls-docker-install installer (jar) Manifest file changes. The wcs-wls-docker-install.jar is the one that does the RCU and the ConfigWizard step for Oracle WebCenter Sites.
Ant jars need to be referred from Weblogic's oracle_common libraries as it's no longer shipped with Sites product.
> ant jar path changed to Weblogic's oracle_common

- CONTRIBUTING.md
Any new product image should be using oraclelinux:8 as its base
layer from 2021.
> [enh] Change default base OS version to oraclelinux:8

- OracleDatabase/SingleInstance/samples/kubernetes/kubernetes-example.yaml
Correcting [SingleInstance/samples/kubernetes/kubernetes-example.yaml](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/samples/kubernetes/kubernetes-example.yaml) file by including security context in the deployment for running the processes with the UID 54321 inside the container.
close #1868 
> Fixing issue #1868

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/checkDBStatus.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
My proposition for solving https://github.com/oracle/docker-images/issues/1651:
Create new externally mapped `oracle` user for health checks who only connects and executes following: `SELECT DISTINCT open_mode FROM v$database`.
User creations happens on DB initial creation
Signed-off-by: Andrzej  Pauli andrzej.pauli@gmail.com
> Fixes excessive audit logs for sys healthchecks #1651

- OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/deployment.yaml
- OracleDatabase/SingleInstance/helm-charts/oracle-db/values.yaml
To Deploy Kubernetes pods of OracleDatabase only on nodes in a particular NodePool having label "pool" , Added label "pool" under nodeSelector in OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/deployment.yaml
> To Deploy kubernetes pods of OracleDatabase only on nodes in a particular nodepool having label "pool"

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
- OracleDatabase/SingleInstance/helm-charts/oracle-db/README.md
- OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/_helpers.tpl
- OracleDatabase/SingleInstance/helm-charts/oracle-db/values.yaml
Enable support to turn on archive log mode in the database while creating the container or deploying using 19c docker image.
Raised issue #1902 for this PR.
Close #1902 
> Support to turn on archive log mode in the database

- .github/workflows/build-and-push-dev-images.yml
- .github/workflows/build-and-push-instantclient-images.yml
- .github/workflows/build-and-push-nosql-image.yml
This provides extra security by not requiring repository or org
level secrets. Includes tweaking the individual builds to still
publish to the Oracle namespace. This required updating the
permissions for each package to allow this repo to push.
> ci: update build and push workflows to use GITHUB_TOKEN

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh
Adding option to buildContainerImage.sh for providing image_name:tag of the generated image.
> Option to provide image name and tag while generating docker image

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/setPassword.sh
If archive_log mode is turned on after providing the ENABLE_ARCHIVELOG=true at docker run command, the inclusion of archive_logs directory in $ORACLE_BASE/oradata/$ORACLE_SID/ directory creates problem in ORACLE_PDB determining logic in the setPassword script. So, fixing this logic.
close #1942 
> setPassword script fix

- OracleDatabase/SingleInstance/README.md
The `-i` option should not be used in copy/pastable code within the documentation.
The checksum functionality (which `-i` skips) is there to ensure users have downloaded the correct (and not corrupt) Oracle Database ZIP file which is needed to build an image.
> Remove -i from documented build command

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/setupLinuxEnv.sh
- OracleDatabase/SingleInstance/extensions/k8s/Dockerfile
- OracleDatabase/SingleInstance/extensions/k8s/startDB.sh
- OracleDatabase/SingleInstance/extensions/patching/Dockerfile
If users mount `/opt/oracle/scripts/setup` and` /opt/oracle/scripts/startup` directories from host machine while creating the container from the extended image (either using patching or k8s extension), some scripts which are already present in those locations (kept there while extending the base docker image) are overwritten.
So created new directories `/opt/oracle/scripts/extensions/setup` and `/opt/oracle/scripts/extensions/startup` to place the scripts while extending the base image. Now, It doesn't get overwritten even if user mount the directories mentioned above.
> Fix user script mount issues related to extensions

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
- OracleDatabase/SingleInstance/extensions/k8s/Dockerfile
If one of the database pods which is initialising database , is killed/stopped before it's ready , the other pods try to create the database and result in Pod Crash  #1969 
Solved this by creating a checkpoint file and checking if it is present before creating or starting database.
> DB crash when container is killed/stopped before DB is ready .

- OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/NOTES.txt
Help text displays <nodeport-ip> as $NODE_IP even when loadBalService is set to true in values.yaml . #1974 
Modified the same to display <loadBalancer-ip> as $NODE_IP when loadBalService is set to true in values.yaml
> Modify help text displayed during helm install

- OracleDatabase/SingleInstance/extensions/patching/Dockerfile
- OracleDatabase/SingleInstance/extensions/patching/runDatapatch.sh
Added a env variable SKIP_DATAPATCH which if set to true , skips datapatch .
> Option to skip datapatch for read-only/standby databases

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/relinkOracleBinary.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
When a container starts with ORACLE_SID whose database installation is incomplete , clean up the datafiles 
Removed SID entry in oratab .
Removed $ORACLE_BASE/cfgtoollogs/dbca/$ORACLE_SID
Removed $ORACLE_BASE/admin/$ORACLE_SID
Removed $ORACLE_BASE/oradata/$ORACLE_SID
Changed location of checkpoint file .
> Proper cleanup of datafiles

- OracleLinuxDevelopers/oraclelinux7/ruby/3.0/Dockerfile
Added Ruby 3 support (Ruby 3.0.1), installed from OL7 repo.
Signed-off-by: Ewan Slater <ewan.slater@oracle.com>
> Ruby 3.0.1 installed from OL7 repo

- OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh
In the view of preparing for newer releases, latest version should be automatically populated in `VERSION` variable (not hard-coded) of buildContainerImage.sh script.
Close #1993 
> Obtaining latest version in buildContainerImage script

- OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/12.2.0.1/runOracle.sh
- OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/18.3.0/runOracle.sh
- OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/19.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/18.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
The memory check in the runOracle script takes the cgroup version into
account.
Fixes #1939
> fix(database): cgroup v2 compatibility

- OracleDatabase/SingleInstance/extensions/sharding/Dockerfile
- OracleDatabase/SingleInstance/extensions/sharding/README.md
Used **multi-stage builds**: 
- In first stage downloaded the entire repository from [oracle/db-sharding](https://github.com/oracle/db-sharding) using `Curl` utility. 
- In the second stage copy the necessary scripts from the previous stage, to the `$ORACLE_HOME/scripts/sharding` directory of the image to build sharding extension.
> Sharding extension for SIDB container image

- CONTRIBUTING.md
We do not recommend using oraclelinux:8-slim for any image that
needs to install additional packages.
> fix(doc): Update the contribution guide to be more specific

- .github/workflows/build-and-push-dev-images.yml
- OracleLinuxDevelopers/oraclelinux8/compat/8-slim/Dockerfile
This image adds microdnf to the oraclelinux:8 image so that any
downstream automation continues to work after the replacement of
the current oraclelinux:8-slim base image.
This the first step and is required to update #2020 to reference 
the right base image.
> feat(dev-images): create a base image for compatibility purposes

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
Close #2073 
Added support for Oracle Wallet for SingleInstance 19c. If the wallet is present (represented by `WALLET_DIR` env var), the wallet is used for database creation, not `ORACLE_PWD`.
Thus, in the kube environment, we can create oracle wallet using some init container and there will not be any need of passing the password in the form of `ORACLE_PWD` env var.
This way, database password will not persist as an env variable in the pod environment.
> Adding support for oracle wallet in the pod environment for 19c

- OracleLinuxDevelopers/oraclelinux7/golang/1.13/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/golang/1.15/Dockerfile
- OracleLinuxDevelopers/oraclelinux7/golang/1.16/Dockerfile
Add a a golang 1.16 specific container. For now it will generate the
same container as the one in the `golang` directory, but it "locks" the
version on 1.16.
It will also be built by the `build-and-push-dev-images` action.
Also update containers from previous golang version to disable any
pre-set golang channel. This will avoid issue if/when 1.16 is no more
the default version.
> feat(developper):  add golang 1.16 container

- OracleGoldenGate/21c/Dockerfile
- OracleGoldenGate/21c/nginx/nginx.conf
- Also listen for HTTP on port 80 for downstream reverse proxies.
> Oracle GoldenGate in a Container

- OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkDBStatus.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkSpace.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createObserver.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/installDBBinaries.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/relinkOracleBinary.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/runUserScripts.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/setupLinuxEnv.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/startDB.sh
Static analysis of 21c scripts performed by ShellCheck utility. In this PR, incorporated all the suggestions generated by the tool without breaking the functionality.
Mostly issues were:
- Using double quotes to prevent word splitting
- Not using legacy backtick(``) notation, instead using $() notation.
> Static check issues resolution for 21c scripts

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createObserver.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/dbca.rsp.tmpl
For 21c, DBCA option `-autoGeneratePasswords` used for generating passwords automatically while creating the database. The user has to change this password **mandatorily** using `setpassword.sh` script after the database is created and the corresponding container is healthy. This new password will be used afterwards by the user to connect with the database.
> Using DBCA option -autoGeneratePasswords while creating the database

- OracleLinuxDevelopers/README.md
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>
> Add golang 1.17 for OL7 to README, remove 1.15

- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
To make intermediate dbca template more secure while database creation, `umask 177` is used. This file creation mask was unintentionally causing problem in connecting to the **PDB** i.e. **ORCLPDB1** using **SQLPlus**.
So, after the the template files are created, the file creation mask is reverted to it's original value i.e. 022. This solves the connectivity problem.
> Reverting file creation mask to original value after dbca template creation

- OracleSOASuite/dockerfiles/12.2.1.4/Dockerfile
- OracleSOASuite/dockerfiles/12.2.1.4/README.md
- OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/createDomainAndStart.sh
- OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/get_healthcheck_url.sh
- OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/soaExtFun.sh
- OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/startAS.sh
- OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/startMS.sh
- OracleSOASuite/dockerfiles/12.2.1.4/container-scripts/updListenAddress.py
- OracleSOASuite/dockerfiles/12.2.1.4/install/b2b.response
- OracleSOASuite/dockerfiles/12.2.1.4/install/osb.response
- OracleSOASuite/dockerfiles/12.2.1.4/install/soasuite.response
- OracleSOASuite/dockerfiles/buildDockerImage.sh
Hi,
This pull request contains the below changes for Oracle SOA Suite docker image scripts. 
Kindly review and merge. 
- Fix for the github issue 2077 (https://github.com/oracle/docker-images/issues/2077) - SOA servers port mapping related changes
- Fix for the github issue 2051 (https://github.com/oracle/docker-images/issues/2051) - Healthcheck related changes
- Copyright corrections
- SOA Docker image build script changes.
Thanks
Samba
> fix for issues 2077,2051 and build script fixes

- OracleLinuxDevelopers/oraclelinux7/nodejs/14/Dockerfile
There was a missing closing bracket for the command in the Node.js 14 Dockerfile.
> Fix Node.js 14 Dockerfile

- CODEOWNERS
> fix: sort CODEOWNERS alphabetically by first-level directory name

- OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
close #1797 
Using `unbuffer` utility from `expect` package to show progress when 18c XE image is being built, so it does not appear to be hanged.
> Fix: Oracle XE 18c image build appears to hang

- .github/workflows/build-and-push-dev-images.yml
- OracleLinuxDevelopers/oraclelinux8/gcc-toolset/11-perftools/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/gcc-toolset/11-perftools/entrypoint.sh
- OracleLinuxDevelopers/oraclelinux8/gcc-toolset/11-toolchain/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/gcc-toolset/11-toolchain/entrypoint.sh
Test builds of the images are available via my fork at https://github.com/Djelibeybi/docker-images/pkgs/container/oraclelinux8-gcc-toolset. 
Resolves #2185.
> feat: add gcc-toolset-11 toolchain and perftool images.

- OracleRestDataServices/dockerfiles/ords_params.properties.tmpl
Enabling Database API as a ORDS Default Feature .
As we don't get a console during docker runtime to choose between available features:
`Enter a number to select a feature to enable: 
[1] SQL Developer Web  (Enables all features)
[2] REST Enabled SQL
[3] Database API 
[4] REST Enabled SQL and Database API 
[5] None`
Running the docker image built directly by cloning the present OracleRestDataService Repo would fail in the above step , and ORDS would fail to install successfully.
So Enabling one feature by default would install the ORDS Successfully and one can anytime enable other features manually using ords.war
> Enabling Database API as a ORDS Default Feature

- OracleDatabase/SingleInstance/extensions/k8s/Dockerfile
Extending the image for prebuilt db with a k8s extended image is defaulting ORACLE_SID to ORCLCDB
So removed it as env
> Removed ORACLE_SID from env variables in k8s extension

- OracleDatabase/SingleInstance/extensions/k8s/checkDBLockStatus.sh
- OracleDatabase/SingleInstance/extensions/k8s/runOracle.sh
Close #2221 
After building k8s extension, health-check was failing for DG Observer. Fixed in this PR.
> Bugfix: Healthcheck fix for dg observer

- OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile.xe
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
Close #2214 
Due to wrong location of ORACLE_BASE_HOME env var, listener was not able to restart either after snapshoting the image using `docker commit` and restarting it. This issue is fixed in this PR.
> Bugfix: listener fail to restart 21c XE

- OracleLinuxDevelopers/oraclelinux8/gcc-toolset/11-perftools/entrypoint.sh
- OracleLinuxDevelopers/oraclelinux8/gcc-toolset/11-toolchain/entrypoint.sh
Use `env` instead of `bash -c` to run the command line.
`bash` isn't strictly necessary and it is easier to pass argument through `env` 
An alternative would be to use `bash -c "$(printf '%q ' "$@")"` but it is more convoluted and doesn't bring anything...
Fixes #2229
> fix(developer):  use env to run command line.

- OracleLinuxDevelopers/oraclelinux8/python/3.8/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/python/3.9/Dockerfile
We should probably add some tests to check that the version of Python indicated by the tag is the version of Python actually installed in the image.
> fix: install the correct version of Python

- CODEOWNERS
- NoSQL/19.5-ce/Dockerfile
- NoSQL/README.md
- NoSQL/ce/Dockerfile
- NoSQL/ce/start-kvlite.sh
This PR updates the Oracle NoSQL Dockerfile to align with the latest version and bundles. 
- Currently, this GitHub uses the bundle kv-ce-19.5.19.zip to build the docker image. Our last bundle for this version is kv-ce-19.5.25.zip. 
- We created a new directory ce. It contains the Dockerfile for the latest Oracle NoSQL version, 20.3.
- In this new version, we are also adding HTTP PROXY support
- I also explicitly set the base image to the Oracle Linux-based 8 variant of the official OpenJDK image.
Finally, I updated CODEOWNERS to switch the owner of /NoSQL to @dario-vega and @mikebrey. 
Signed-off-by: Dario Vega dario.vega@oracle.com
> NOSQL - Update kv version and doc

- OracleDatabase/SingleInstance/extensions/k8s/lock.py
Fixing locking script i.e. lock.py in k8s extension to support proper locking with nfs4.
> Fix lock.py in k8s extension for NFSv4

- .github/workflows/build-and-push-nosql-image.yml
- NoSQL/README.md
- NoSQL/ce/Dockerfile
- NoSQL/ce/start-kvlite.sh
This PR updates with some improvements to the Oracle NoSQL CE image.
Provide a solution to https://github.com/oracle/docker-images/issues/1594 - ADVANCED CONFIGURATION
Avoid installing new packages - not using anymore `microdnf install unzip hostname`
When restarting the container, KVLITE refuses to start because of the hostname change. Use -hostname when executing the command run.
Finally, I updated build-and-push-nosql-image.yml
moving from a release-based tag to a date-based tag
changing the paths
Signed-off-by: Dario Vega dario.vega@oracle.com
> Update the NoSQL Image

- OracleLinuxDevelopers/oraclelinux8/php/7.4-apache-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.4-cli-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/php/7.4-fpm-oracledb/Dockerfile
@cjbj could you please [test the images built over in my fork](https://github.com/Djelibeybi/docker-images/pkgs/container/oraclelinux8-php) to make sure everything works as expected?
> feat: add Oracle DB enabled PHP 7.4 images based on Oracle Linux 8

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
The bug is with respect to PR #2238 
Respective change is required in 19.3.0 runOracle.sh script, otherwise its causing the 19c container to fail ([Ref](https://github.com/oracle/docker-images/pull/2238#issuecomment-1065252008))
Fixed by adding the required code.
> Oracle DB 19c Bugfix

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh
Provisioning password change with `ORACLE_PWD` while running the extended image with **prebuiltdb** extension, using `docker run` command.
Created a state-file with location as `${ORACLE_BASE}/oradata/{ORACLE_SID}/.prebuiltdb` to indicate that the image is extended with **prebuiltdb** extension. When this file is present, and `ORACLE_PWD` is passed to `docker run` command, this PR allows to change the password.
> Password change while running prebuiltdb extended image

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/checkDBStatus.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh
To specify the password securely(for sys, system and pdbadmin accounts), support for podman secrete provided. The user can create a secret using `podman secret create` command. The name of the secrete should be **oracle_pwd**. After this, user can specify this secret using the `--secret=oracle_pwd` option in the `podman run` command.
EDIT: supported from Oracle Database 21.3.0 onwards
> Podman secret support(mount mode only)

- OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
If `ORACLE_PWD` is passed in `docker run` command while running the database container image extended with **prebuiltdb** extension, don't allow user to change the password using `setPassword.sh` script. As the password is in the environment and if the container is restarted, then the changed password will not persist. The password will revert back to the one which exists in the environment.
> setPassword script condition for prebuiltdb extended image

- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
By default, Oracle EM Express is available only from the local server in 21c XE. This PR has the changes to make it accessible remotely.
> Making Oracle Database EM Express available remotely for XE 21.3

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile
Support for containerizing  on-premise databases by using CLONE_DB option along with README changes.
+ Fixing podman secret create command in the README.
> Support for Containerizing On-premise databases

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile.xe
- Added a Readme section to specify the environment variables required to build the container images using Podman.
- Added `--timeout` option in the` HEALTHCHECK` instruction in the Dockerfiles (19c onwards). If not set, it takes the default value of 0 while using podman and always shows status `unhealthy` while running the container image in Podman. Value of the timeout kept as 30s which is default in Docker environment.
> Changes required to build Oracle Database container images using Podman

- NoSQL/ce/start-kvlite.sh
This PR updates with some improvements to the Oracle NoSQL CE image.
HTTP proxy waits for kvstore to start. Adding a while, so that the Oracle NoSQL Database Proxy didn't exit and wait for the kvstore to start
> NoSQL Database Proxy waits for kvstore to start.

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/checkDBStatus.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/setPassword.sh
- Podman secret support for Oracle Database 19.3.0
- Added condition in `setPassword.sh` script, for preventing user to change the password if it is in environment for a prebuiltdb extended 19c image container.
> Podman secret support for Oracle Database 19c

- OracleJava/11/Dockerfile
- OracleJava/11/Dockerfile.8
- OracleJava/17/Dockerfile
- OracleJava/17/build.sh
- OracleJava/18/Dockerfile
- OracleJava/18/build.sh
- OracleJava/8/Dockerfile
- OracleJava/8/Dockerfile.8
- OracleOpenJDK/18/Dockerfile
Updated the versions to match the May patch update that replaced the April 2022 CPU.  Also changed the dockerfiles for JDK 11, 17, and 18 to be able to build either x86-64 or aarch64. (serverJRE 8 is only available as x86-64 that version is just an update from 8u331 to 8u33)
> April cpu patch

- OracleManagementAgent/README.md
- OracleManagementAgent/dockerfiles/latest/Dockerfile
- OracleManagementAgent/dockerfiles/latest/container-scripts/watchdog.sh
- OracleManagementAgent/dockerfiles/latest/user-scripts/init-agent.sh
With this change users can provide custom commands to execute each time before Management Agent starts inside the container.
> Oracle Management Agent in a Container - support user script execution

- OracleManagementAgent/README.md
- OracleManagementAgent/dockerfiles/latest/container-scripts/watchdog.sh
- OracleManagementAgent/dockerfiles/latest/docker-compose.yml
This change allows running Management Agent inside a container as root and thus allowing access to root owned locations only within the container.
> Oracle Management Agent in a Container - support agent run as root user

- OracleGoldenGate/21c/bin/deployment-init.py
- On slower systems, the Service Manager application is not detected
correctly. This change makes the OGG initialization logic to wait
for Service Manager to launch before updating its configuration.
> Make GoldenGate wait for Service Manager to launch

- OracleManagementAgent/dockerfiles/latest/container-scripts/watchdog.sh
set -u in a script causes the script to abort if the variable being referenced is not set, using default expansions for the RUN_AGENT_AS_USER variable
> use default expansions for run as agent user variable

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh
- OracleDatabase/SingleInstance/extensions/k8s/swapLocks.sh
Database checkpoint file (empty file) creation is facing some latency issues when NFS is used as a persistent storage in multi-replica mode (kubernetes deployment). To resolve this, populating the checkpoint file with the current date. By doing it, it is not buffered and directly written to the NFS storage.
> k8s extension fix for NFS

- .github/workflows/build-and-push-oci-cli-image.yml
- OracleCloudInfrastructure/README.md
- OracleCloudInfrastructure/oci-cli/Dockerfile
- OracleCloudInfrastructure/oci-cli/README.md
This image has been tested by the OCI CLI team, is based on the Oracle Linux 8 with Python 3.6 image elsewhere in the repo and installs the OCI CLI directly from PyPi which is the most up-to-date authorative source.
> Add OCI CLI container image and documentation

- OracleCloudInfrastructure/oci-cli/Dockerfile
> Use Python 3.9 as Cryptography has deprecated support for Python 3.6

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh
Support for setting cpu_count and processes init parameters during the database creation for the first time by passing `INIT_CPU_COUNT` and `INIT_PROCESSES` options in the `docker run` command.
> cpu_count and processes init parameters support

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/configTcps.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/configTcps.sh
While using `docker exec -it /opt/oracle/configTcps.sh`, ORACLE_SID was turning out to be empty. Fixed by getting proper value of ORACLE_SID from oratab and ORACLE_PDB from oradata/ORACLE_PDB directory.
close #2441 
> Fix in configTcps.sh script

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/configTcps.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/configTcps.sh
- Taking ORACLE_PDB from the env or default it accordingly (XEPDB1 or ORCLPDB). Because the existing method does not work with clone database functionality.
- Increasing the key size to 2048 bytes.
EDIT:
Changing the default tcps port to 2484. Ref: [https://docs.oracle.com/en/database/oracle/oracle-database/12.2/netrf/protocol-address-configuration.html#GUID-71A0702F-A5C6-4122-907D-5E9BFA1DCE45](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/netrf/protocol-address-configuration.html#GUID-71A0702F-A5C6-4122-907D-5E9BFA1DCE45)
> ORACLE_PDB fix in configTcps.sh script

- .github/workflows/build-and-push-oci-cli-image.yml
- OracleCloudInfrastructure/oci-cli/Dockerfile
Also removed the hard-coded repo owner string to allow downstream forks to successfully test/run the workflow.
> Expose OCI CLI image build time values at runtime via environment variables

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/configTcps.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/configTcps.sh
- Taking password from standard input for wallet
- Using 8 byte long randomly generated password for wallet
- Reducing cert validity for 1yr
> Some fixes in configTcps.sh

- OracleDatabase/SingleInstance/README.md
There is a space missing after 2484 which will make the script throw an error
> FIxed docker run missing space

- OracleDatabase/SingleInstance/README.md
Targeted at Issue : #2582 
Changed documentation for connecting to the database container as per '[Easy Connect](https://download.oracle.com/ocomdocs/global/Oracle-Net-21c-Easy-Connect-Plus.pdf)' syntax
```
sqlplus sys/<your password>@//localhost:1521/<your service name> as sysdba
sqlplus system/<your password>@//localhost:1521/<your service name>
sqlplus pdbadmin/<your password>@//localhost:1521/<Your PDB name>
```
> correcting OracleDatabase/SingleInstance/readme.md

- OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux8/python/3.6-oracledb/Dockerfile
Update Linux Python / Oracle Database images to use python-oracledb in preference to its predecessor cx_Oracle.
> Update from cx_Oracle to python-oracledb

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/configTcps.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/configTcps.sh
Fixes https://github.com/oracle/docker-images/issues/2596
This PR adds changes to pass wallet password as an optional argument to `configTcps.sh`
I have tested the changes in the docker container:
1. Create a Database server and client wallet using a custom password
```bash
./configTcps.sh 16002 `hostname` <wallet_pwd>
```
2. Export server's certificate using the same wallet password
```bash
orapki wallet export -wallet "/opt/oracle/oradata/dbconfig/.tls-wallet" \
-pwd <wallet_pwd> \
-dn "CN=localhost" \
-cert `hostname`-certificate.crt
```
3. Successfully exported server's certificate 
```
Oracle PKI Tool Release 19.0.0.0.0 - Production
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.
Operation is successfully completed.
```
> Pass wallet password as an optional positional argument

- OracleDatabase/SingleInstance/extensions/README.md
The readme file inside the extensions folder has an incorrect file name (buildDockerImage.sh instead of buildContainerImage.sh)
> Fixed extentions readme file

- .github/workflows/build-and-push-dev-images.yml
Rather than using an obscure test in `build-and-push-dev-images.yml` to determine if we build for `arm64` or not, I propose to use a `.skip-arm64` file marker for the ones where we only want an `amd64` image.
Other than that, there is no change in the outcome, except we now build `oraclelinux8-python:3.6-oracledb` for arm64 as well.
--
> ci: use `.skip-arm64` to build only amd64 images

- OracleDatabase/SingleInstance/README.md
Adding a readme change to make it clear that 23c FREE doesn't need any binaries to be downloaded in the `dockerfiles/<version>` folder
> Updating -- SIDB readme

- OracleDatabase/SingleInstance/README.md
- OracleDatabase/SingleInstance/dockerfiles/19.3.0/configTcps.sh
- OracleDatabase/SingleInstance/dockerfiles/21.3.0/configTcps.sh
- OracleDatabase/SingleInstance/dockerfiles/23.2.0/configTcps.sh
Added Disable_oob=on in sqlnet.ora of db wallet in configTcps.sh
For version 19 and 21c.
Tested both tcp and tcps connection thereafter.
> tcps db conn fix : disabled oob in sqlnet.ora of DB wallet

- OracleDatabase/SingleInstance/dockerfiles/23.2.0/Containerfile.free
Resolved bashrc creation in wrong location issue in 23.2 free database. It is supposed to be created inside /home/oracle/ and not inside /root.
> Updated to resolve bashrc file creation in wrong location in 23.2 free

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile
This issue 2660 was caused while trying to fix a lint issue. Fixed by updating Dockerfile.
> Fixed issue 2660 (arm64 container fails to start)

- OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh
Fixed condition check for edition in runOracle.sh on arm64 platforms. ORACLE_EDITION is optional parameter for podman run. So if we don't pass it then also podman run command should not fail/exit.
> Fixed condition check for edition in runOracle.sh for arm64 platforms

- OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile.xe
Resolved bashrc creation in wrong location issue in 21.3xe database. It is supposed to be created inside /home/oracle/ and not inside /root.
> Fixing bashrc creation in incorrect loc 21.3xe

- OracleJava/11/Dockerfile
- OracleJava/11/Dockerfile.8
- OracleJava/8/jdk/Dockerfile
- OracleJava/8/jdk/Dockerfile.8
- OracleJava/8/serverjre/Dockerfile
- OracleJava/8/serverjre/Dockerfile.8
- OracleOpenJDK/21/Dockerfile
Change the files and checksums for JDK 11, 8, serverJRE, and OpenJDK to match the Oct 2023 CPU
> Java oct2023 cpu

- OracleJava/11/Dockerfile
- OracleJava/11/Dockerfile.8
- OracleJava/8/jdk/Dockerfile
- OracleJava/8/jdk/Dockerfile.8
- OracleJava/8/serverjre/Dockerfile
- OracleJava/8/serverjre/Dockerfile.8
- OracleOpenJDK/22/Dockerfile
Update the versions and checksums to match the April Critical Patch Update releases.
> updated to April 2024 Critical Patch Update versions

- OracleGoldenGate/23/Dockerfile
- OracleGoldenGate/23/README.md
- OracleGoldenGate/23/bin/create-certificate.sh
- OracleGoldenGate/23/bin/deployment-init.py
- OracleGoldenGate/23/bin/deployment-main.sh
- OracleGoldenGate/23/bin/healthcheck
- OracleGoldenGate/23/bin/replace-variables.sh
- OracleGoldenGate/23/install-deployment.sh
- OracleGoldenGate/23/install-prerequisites.sh
- OracleGoldenGate/23/nginx/nginx.conf
- OracleGoldenGate/23/nginx/ogg-headers.conf
- OracleGoldenGate/23/nginx/ogg.conf
- OracleGoldenGate/23/samples/README.md
- OracleGoldenGate/23/samples/docker-compose.yml
- OracleGoldenGate/README.md
- Initial files to support containerized execution of Oracle GoldenGate 23
> Oracle GoldenGate

- NoSQL/README-sec.md
- NoSQL/README.md
- NoSQL/ce-sec/Dockerfile
- NoSQL/ce/Dockerfile
This PR updates the Oracle NoSQL Dockerfile to align with the latest version and bundles.
-  Our last bundle for this version is `kv-ce-23.3.32`
- It uses the new `DOWNLOAD_FILE` in OTN `community-edition-${KV_VERSION}.zip` instead of `kv-ce-${KV_VERSION}.zip`
>  NOSQL - Update to version 23.3.32

- OracleTuxedo/core/dockerfiles/buildContainerImage.sh
Fixes #2837.
This changes allows the `PROXY_SETTINGS` variable to be word split (as is done in [other build scripts](https://github.com/oracle/docker-images/blob/fa24c6d56a6df05a54dd5c75e6f17ce025f2bde6/OracleWebLogic/dockerfiles/buildDockerImage.sh#L179)) rather than treated as a single argument to the `docker` command. This ensures that the `docker` command is constructed correctly to enable the use of the `https_proxy` environment variable.
> Allow word splitting proxy variable in Tuxedo build script

- OracleInstantClient/oraclelinux7/21/Dockerfile
- OracleInstantClient/oraclelinux8/21/Dockerfile
- OracleInstantClient/oraclelinux8/23/Dockerfile
- OracleInstantClient/oraclelinux9/19/Dockerfile
- OracleInstantClient/oraclelinux9/23/Dockerfile
Change a few usages of 'docker' to podman.
Add links the the base files so users who take/share copies know where to find the originals.  Similar changes were made to 19c files in https://github.com/oracle/docker-images/pull/2862
> Update Instant Client dockerfile comments

- OracleJava/23/Dockerfile
- OracleJava/23/build.sh
- OracleJava/README.md
- OracleOpenJDK/23/Dockerfile
- OracleOpenJDK/23/build.sh
- OracleOpenJDK/README.md
Updated docker files for JDK 22 so that it now builds JDK 23. 
JDK 22 was not a long-term-support release so the launch of JDK 23 supersedes it.
> Updated JDK 22 to JDK 23

- OracleInstantClient/oraclelinux7/19/Dockerfile
- OracleInstantClient/oraclelinux8/19/Dockerfile
Update container for Instant Client 19.23
> Update for Instant Client 19.23

- OracleJava/11/Dockerfile
- OracleJava/11/Dockerfile.ol8
- OracleJava/11/build.sh
- OracleJava/17/Dockerfile
- OracleJava/21/Dockerfile
- OracleJava/21/Dockerfile.ol9
- OracleJava/21/build.sh
- OracleJava/23/Dockerfile
- OracleJava/23/build.sh
- OracleJava/8/jdk/Dockerfile
- OracleJava/8/jdk/Dockerfile.ol8
- OracleJava/8/jdk/build.sh
- OracleJava/8/serverjre/Dockerfile
- OracleJava/8/serverjre/Dockerfile.ol8
- OracleJava/8/serverjre/build.sh
- OracleJava/README.md
- OracleOpenJDK/23/Dockerfile
- OracleOpenJDK/23/build.sh
JDK 17 is no longer available under no fee-term-and-conditions so it now requires users to download the binary first, as was the case before for JDK 8 and JDK 11.
Update the checksums for 11 and 8, and the download URL for OpenJDK 23.0.1
> updated release versions to the Oct 2024 CPU.  JDK 17.0.13 has a new license so it has to be download before building.

- OracleInstantClient/oraclelinux7/19/Dockerfile
- OracleInstantClient/oraclelinux8/19/Dockerfile
Update Instant Client to 19.25
> Update Instant Client to 19.25

- OracleOpenJDK/23/Dockerfile.ol9
updated download url and filename in the OpenJDK dockerfile from 23.0.1 to 23.0.2 per the Jan 2025 Critical Patch Update.
> OpenJDK update to Jan 2025 Critical Patch Update

- OracleHTTPServer/README.md
- OracleHTTPServer/dockerfiles/14.1.2.0.0/container-scripts/start-ohs.py
- OracleHTTPServer/dockerfiles/14.1.2.0.0/container-scripts/stop-ohs.py
Correct NM calls, Copyrights, Documentation link
> Correct NM calls, Copyrights, Documentation link 

- OracleDatabase/RAC/OracleDNSServer/README.md
- OracleDatabase/RAC/OracleDNSServer/README1.md
- OracleDatabase/RAC/OracleRACStorageServer/README.md
- OracleDatabase/RAC/OracleRealApplicationClusters/README.md
- OracleDatabase/RAC/OracleRealApplicationClusters/docs/DELETION.md
- OracleDatabase/RAC/OracleRealApplicationClusters/docs/ENVIRONMENTVARIABLES.md
- OracleDatabase/RAC/OracleRealApplicationClusters/docs/developers/OTHERS.md
- OracleDatabase/RAC/OracleRealApplicationClusters/docs/developers/README.md
- OracleDatabase/RAC/README.md
- OracleDatabase/README.md
Fixes-
1. DNS README.md file
2. Fix missing links and remove OL7 references
> Minorfixes

- OracleLinuxDevelopers/README.md
- OracleLinuxDevelopers/oraclelinux8/python/3.12-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux9/python/3.11-oracledb/Dockerfile
- OracleLinuxDevelopers/oraclelinux9/python/3.12-oracledb/Dockerfile
- Added new python-oracledb images
- Did a pass through the Linux README and added basic missing info.  The owner (@AmedeeBulle ?) should do further updates to add missing info about existing containers.
> Add new python-oracledb images

- NoSQL/README-sec.md
- NoSQL/README.md
- NoSQL/ce-sec/Dockerfile
- NoSQL/ce/Dockerfile
This PR updates the Oracle NoSQL Dockerfile to align with the latest version and bundles.
- Our last bundle for this version is `kv-ce-24.4.9`
- Using `ghcr.io/graalvm/jdk-community:21` instead of `ghcr.io/graalvm/jdk:ol9-java17`
> NOSQL - Update to version 24.4.9

- Archive/ContainerCloud/images/rolling-router-sticky-sessions/README.md
- CONTRIBUTING.md
- OracleDatabase/OracleConnectionManager/README.md
- OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/12.2.0.1/sshUserSetup.sh
- OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/18.3.0/sshUserSetup.sh
- OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/19.3.0/sshUserSetup.sh
- OracleDatabase/RAC/OracleRealApplicationClusters/docs/rac-container/racslimimage/README.md
- OracleDatabase/SingleInstance/FAQ.md
Fixes typos in Markdown and Shell files.
> misc: fix grammar and spelling

- OracleGoldenGate/23/README.md
As part of our internal testing and validation efforts, we have successfully certified the this repo for use with the following:
- Oracle GoldenGate 23.4 Microservices for MSSQL on Linux x86-64
- Oracle GoldenGate 23.4 Microservices for MYSQL on Linux x86-64
- Oracle GoldenGate 23.8 Microservices for Distributed Applications and Analytics on Linux x86-64
These have been tested in line with the existing validations already done for PostgreSQL and Oracle.
> Update OracleGoldenGate 23 readme with new supported platforms

- OracleGoldenGate/23/README.md
- OracleGoldenGate/23/bin/deployment-main.sh
I'm using this image to install GoldenGate and I need to run python scripts whenever a container starts.
I've added support for python scripts on startup.
> OracleGoldenGate 23 - Adding support for python startup scripts

- OracleJava/11/Dockerfile.ol8
- OracleJava/17/Dockerfile.ol8
- OracleJava/8/jdk/Dockerfile.ol8
- OracleJava/8/serverjre/Dockerfile.ol8
- OracleJava/README.md
Java Management Service (JMS) has been updated to no longer require users to specify OCI_REGION when downloading releases.   Simplified the dockerfiles by removing that argument
> Removed the need to pass the OCI region as an argument to the dockerfiles
